### ISSUE TITLE
Old BuildingSpawner.c null and void?

### ISSUE THREAD

**Issue by exm316** [Da0ne/DZMods#100]
Am I correct in thinking that the old BuildingSpawner.c is now null and void? and do you now add the buildings and locations at the bottom of Tunables.c?

mpmissions\DayZSurvival.chernarusplus\ScriptedMods\Modules\Misc

If so should this be removed or left in place?

**Comment by chawdinky** [comment]
Its planned to be removed

**Comment by exm316** [comment]
Also - can this be run server side only for the admin control features? Obviously the client side functions will not work or be available for players!

**Comment by exm316** [comment]
Thats cool..... But if a player does not have the mods installed will they still be able to join the server?

**Comment by GravityWolfNotAmused** [comment]
No, they need to use the steam workshop, and dayz launcher/start up command to download and launch the game with the add-on. They will be kicked for modified data.

[Here you go](https://github.com/Da0ne/DZMods#-added-map-ui-accessible-by-pressing-insert-comes-with-many-features-and-many-more-features-that-i-cant-be-asked-to-write-downi-hate-doing-readmejust-have-a-look-at-the-screen-shots-on-the-steam-workshop)

**Comment by exm316** [comment]
OK... I can still join my server even with the mods installed and running on it without having them loaded. This is kinda what I want as I don't want to isolate players who don't use the launcher!

Obviously they do not get the loadout and spawn options though....

**Comment by exm316** [comment]
Definitely the last thing - I spawn my buildings in COM and the copy the coordinates etc. from this - is there an easy way to convert the copied data into your new format, or is it a case of manually converting?

**Comment by GravityWolfNotAmused** [comment]
All the information you world normally put into Create Object, goes into SpawnedBuilding, they take the same data.

**Comment by GravityWolfNotAmused** [comment]
Just add more lines of spawned buildings to the function in tunables.c and change your values.
