### ISSUE TITLE
Does SpawnArmed work with staticloadouts?

### ISSUE THREAD

**Issue by Degrath** [Da0ne/DZMods#103]
I have both options enabled in the  Advancedloadouts.c but new characters do not spawn with a weapon unless I create a new staticloadout with a weapon included. Going through the script log shows no errors.

Also weapons added to a staticloadout do not include attachments. The subinventory items save to the file but weapon attachments do not save to weapons in subinventory. Is this normal or a bug?

**Comment by chawdinky** [comment]
No they do not. SpawnedArmed works with random loadout. please close this issue. Thanks ;)
