### ISSUE TITLE
Can't compile “Mission” script module.

### ISSUE THREAD

**Issue by lowrey2142** [Da0ne/DZMods#105]
Can't compile “Mission” script module.
I get the following error when I run with the mod enabled:

![uadropitem_error](https://user-images.githubusercontent.com/42722206/49336148-47c94c00-f5f4-11e8-8e92-7c4e50822358.jpg)

Here is my startup command:
-mod=@RPCFramework;@VanillaPlusPlus -config=XX\serverDZ.cfg -port=2302 -profiles=XX\dayzmaster -bePath=XX\battleye -noFilePatching -cpuCount=8

**Comment by GravityWolfNotAmused** [comment]
I complete installed the mod from fresh dayz install, and server install to current build for both our project and the RPCManager, and have determined that this is 100% due to user error, and is not a valid bug.
