### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by RealShu** [Da0ne/DZMods#106]
Is it possible for me to use the vanilla ++ mod without using the new mission file? I basically just want the death messages etc. I use the old vanila + dzmods since i dont want to mess with the spawn select.

Also for buildings i use the offline editor and when i copied to clipboard it copied all the buildings as - 
spawncustom building instead of "obj.SetOrientation" etc.
Can i convert this somewhere or do I have to manually?

**Comment by GravityWolfNotAmused** [comment]
@RealShu 

> Also for buildings i use the offline editor and when i copied to clipboard it copied all the buildings as -
> spawncustom building instead of "obj.SetOrientation" etc. 
> Can i convert this somewhere or do I have to manually?

All you have to do is:
```c
new SpawnedBuilding("nameOfBuildingHere", "PositionHere", "Orientation here"),
new SpawnedBuilding("nameOfBuildingHere", "PositionHere", "Orientation here"),
new SpawnedBuilding("nameOfBuildingHere", "PositionHere", "Orientation here"),
new SpawnedBuilding("nameOfBuildingHere", "PositionHere", "Orientation here"),
new SpawnedBuilding("nameOfBuildingHere", "PositionHere", "Orientation here"),
new SpawnedBuilding("nameOfBuildingHere", "PositionHere", "Orientation here"),
```
You do not need to call SetOrientation, or SetLocation I do that for you already.

**Comment by RealShu** [comment]
but this is with the new mission file? or the old one. I use the old one.

**Comment by GravityWolfNotAmused** [comment]
Which one? The one with SpawnedBuildings.c ?

**Comment by GravityWolfNotAmused** [comment]
Do you have [these](https://github.com/Da0ne/DZMods/tree/master/mpmissions/DayZSurvival.chernarusplus/ScriptedMods/Modules/CustomBuildings) files?

**Comment by RealShu** [comment]
No i do not. Like I said Im using the old mission file before this big update.

**Comment by RealShu** [comment]
obj = GetGame().CreateObject("Land_Mil_Tent_Big2_5", "819.775391 -57.618027 543.680664");
        obj.SetOrientation("22.000017 0.000000 0.000000");
        obj.SetPosition("12111.414063 141.997147 12660.157227");

and example of the format

**Comment by GravityWolfNotAmused** [comment]
Give me a moment

**Comment by GravityWolfNotAmused** [comment]
Man, I wish you got our update before GUI release, I made this process 100 times simpler...

**Comment by GravityWolfNotAmused** [comment]
And now, I do not have those older files to share with you v.v

**Comment by GravityWolfNotAmused** [comment]
However, you do not need to set obj position, this is the second value you put in CreateObject.

```c
                                                                                                                      |
                                                                                                                     V
obj = GetGame().CreateObject("Land_Mil_Tent_Big2_5", "819.775391 -57.618027 543.680664");

```

**Comment by GravityWolfNotAmused** [comment]
Understand?

**Comment by GravityWolfNotAmused** [comment]
[I hope that at some point you give the newer update a change, I made it so all you had to do was do as shown, and I am about to add loot to those buildings that you choose to spawn through this system.](https://github.com/Da0ne/DZMods/blob/cbe03b664db7cf6b6639c436b434ce6d16efc142/mpmissions/DayZSurvival.chernarusplus/ScriptedMods/Tunables.c#L81-L89)

**Comment by GravityWolfNotAmused** [comment]
If you have the mod on the server than clients should as well. That's just how it has to be for now.
