### ISSUE TITLE
Admins not working correctly

### ISSUE THREAD

**Issue by robotstar78** [Da0ne/DZMods#11]
So, when I installed the mod and got it working, I added my Steamid64 to the admins.txt and everything worked fine.

I also added, another 2 admins from our server. They have been unable to log in as admin. So we did some testing tonight, adding each steamid64 to a separate line, adding them to a single line with commas, semi colons.. .Now none of us can log in as an admin, even if I remove all the other steamID64s and just have mine! Help!

**Comment by robotstar78** [comment]
Update. I can again log in as an admin if I completely close the game and relaunch it. But still I’m the only one who can log in.

Things we’ve tried:

Adding another steamid64 above mine.

Adding a comma between each id. For example: 77283738373, 2726262828, 393837372

Adding on separate lines eg:
8272628282
9292826622
7252627822
7262527839

Adding a semi colon after each Id:

8272828722;
2725272722;
8262628288

Not sure what else to try!

**Comment by Da0ne** [comment]
Only 1 admin at a time can utilize the tool, as the game only allows one #login
As to adding more more players/admins just place the next GUID under the top one.

[This is how it should look](https://gyazo.com/f784b44b06ace4491be2c77b5fe3d748)

**And make sure there are no spaces after each line,**
