### ISSUE TITLE
INFO, add "consomable" to respawn ???

### ISSUE THREAD

**Issue by LArtDesChOiX** [Da0ne/DZMods#112]
I did not find how to add objects "fixed", example water bottle, canned, compass, couplet with the function randomly generated ??

Where should I put them? Before that in the vanilla part

**Comment by GravityWolfNotAmused** [comment]
Do you want to learn how to spawn loot?

**Comment by LArtDesChOiX** [comment]
yes, add "fixe "loot ^^
