### ISSUE TITLE
Kicked upon login

### ISSUE THREAD

**Issue by L33B0B** [Da0ne/DZMods#114]
Hi,
Me again! Still getting login errors when connecting to the server. Everyone regardless of server cfg gets kicked after spawn count down. I've reinstalled the server 3 times to make sure i havent done a stupid config. But its completely vanilla and it still wont allow me to log in.

This is what appears in the console when i try:
![capture](https://user-images.githubusercontent.com/10597088/49405138-7d337e00-f749-11e8-936c-2134519d0704.JPG)

Any ideas??

**Comment by GravityWolfNotAmused** [comment]
There are still files left around from DayZ after you uninstall, those could be the issue? IDK, you guess is as good as mine.

**Comment by AndyLee1024** [comment]
same here
