### ISSUE TITLE
Static Vs Random Loadouts

### ISSUE THREAD

**Issue by James5445** [Da0ne/DZMods#115]
i cant fine the place where i disable random loadouts in tuneables.c

**Comment by GravityWolfNotAmused** [comment]
https://github.com/Da0ne/DZMods/blob/0aceadbc3c53cd67d4cfdc68ad8dfffb4265f732/mpmissions/DayZSurvival.chernarusplus/ScriptedMods/Modules/AdvancedLoadouts/AdvancedLoadouts.c#L4-L6

https://github.com/Da0ne/DZMods/tree/master/mpmissions/DayZSurvival.chernarusplus/ScriptedMods/LoadOuts/RandomlyGenerated

**Comment by James5445** [comment]
ok thank you

**Comment by James5445** [comment]
is there still a problem with the GUI spawn menu cuz i get stuck on the loading screen
