### ISSUE TITLE
Spawned buildings

### ISSUE THREAD

**Issue by sy8282** [Da0ne/DZMods#117]
Are we limited in anyway as to how many extras we spawn it as I have big big plans which require alot of trees bushes etc

**Comment by GravityWolfNotAmused** [comment]
Um, not to my knowledge maybe a server hardware limit. I only tried with 50 object, and only one player, so if you run into any issues let me know.

**Comment by sy8282** [comment]
Do you happen to know which program the devs use to generate forests etc and if that tool has been released as we are looking at adding alot and I mean alot of stuff map wide and would be alot quicker than manually spawning them

**Comment by GravityWolfNotAmused** [comment]
Use the community offline add-on, idt that's those tools are released yet.
