### ISSUE TITLE
static loadouts still not working 

### ISSUE THREAD

**Issue by James5445** [Da0ne/DZMods#118]
I am still stuck on the black spawn screen whenever i try to spawn

**Comment by LArtDesChOiX** [comment]
Same... I use the "selection menu".. I add the item i want !

But i cannot ADD "consumable" :/..... Compass... Pear, water bottle !

**Comment by LArtDesChOiX** [comment]
If you know a solution ^^

**Comment by LArtDesChOiX** [comment]
You need "true" "advanced loadour" in tunable

**Comment by LArtDesChOiX** [comment]
And "protected bool m_StaticLoadouts     = false;"
protected bool m_RandomizedLoadouts = true;

In \ScriptedMods\Modules\AdvancedLoadouts\....

GOOD LUCK

**Comment by LArtDesChOiX** [comment]
And MODIFIE the STUUF "HERE" \DayZSurvival.chernarusplus\ScriptedMods\LoadOuts\RandomlyGenerated\
