### ISSUE TITLE
Building spawner

### ISSUE THREAD

**Issue by sy8282** [Da0ne/DZMods#125]
Just need A yes or no answer,
Can Building spawned using the previous version be used in the new version without editing every item?
Asked before and issue was closed without actually answering the question

**Comment by GravityWolfNotAmused** [comment]
Send me the file, and I will convert them all for you.\

**Comment by GravityWolfNotAmused** [comment]
And no

**Comment by sy8282** [comment]
I'll sort the files out when I can get to a pc it's a few files as got multiple servers could I just use search and replace to edit them quicker? If so I won't take up your time I know you guys are busy

**Comment by sy8282** [comment]
reformatted an area to the new format now everything is out of line some walls in wrong positions etc 
any ideas??

**Comment by S4MT3K** [comment]
I have the Solution. I will make a pull request. Better way is one of the devs will add me anywhere we can chat. Steam would be the best imo. (S4MT3Kツ) @GravityWolfNotAmused

**Comment by Sniy** [comment]
Me have a issue with the Buildings i spawn . 
With the first release i can change the  height and deep from the building .
Land_Mil_Barracks1", "11900.6 141.947 12543.2", "-65 0 0
i changed the middle line "141.947" to "140" and all good . 

But with the new Release i can´t do them , i have flickering on the ground in Barracks . Change the value doens´t work .

Anyone have a tip for me ? (sry for my bad engl.)

**Comment by GravityWolfNotAmused** [comment]
@sy8282 
@Sniy 

https://github.com/Da0ne/DZMods/issues/137#issuecomment-446295710
