### ISSUE TITLE
Issues.

### ISSUE THREAD

**Issue by Niikk0o** [Da0ne/DZMods#127]
`9:44:33 [StateMachine]: Player Survivor (dpnid 1449529290 uid dpNDAxd9hO0R4Wzn40mei16j94t3WVni24qrmQ1zFQ4=) Entering GetNewCharLoginState
 9:44:33 [StateMachine]: Player Survivor (dpnid 1449529290 uid dpNDAxd9hO0R4Wzn40mei16j94t3WVni24qrmQ1zFQ4=) State Error (GetNewCharLoginState): Player with network id 0 not found
 9:44:33 Player Survivor (1449529290) kicked from server: 6 ()
 9:44:33 [StateMachine]: Kick player Survivor (dpnid 1449529290 uid dpNDAxd9hO0R4Wzn40mei16j94t3WVni24qrmQ1zFQ4=) State GetNewCharLoginState Error 
 9:44:33 [Disconnect]: Client 1449529290 normal disconnect
 9:44:33 [Disconnect]: No player -> call DB exit 1449529290 
 9:44:33 [Disconnect]: No player -> remove player info 1449529290 
 9:44:33 [Disconnect]: DisconnectPlayerFinish 1449529290
 9:44:33 [Disconnect]: Remove player info 1449529290`

Fresh files.

**Comment by Bhuddaguy** [comment]
![image](https://user-images.githubusercontent.com/45108922/49620037-43eb5000-f98d-11e8-89ce-ba68a9a33ced.png)
Players are spawning without gear. Advanced Loudouts are enabled, tunables.c hasn't been altered, please avdvise
