### ISSUE TITLE
custom buildings not spawning

### ISSUE THREAD

**Issue by RealShu** [Da0ne/DZMods#129]
I converted all my custom buildings into the correct format but they are not spawning. I have them at the bottom of the tunables like this - 

new SpawnedBuilding("Land_Mil_ATC_Small", "-3521.516113 -179.858383 -11074.205078", "-37.999989 0.000000 0.000000"),

**Comment by RealShu** [comment]
fixed it was putting in the wrong positions coords :()

**Comment by RealShu** [comment]
New question - any idea why the loot is floating in the custom buildings?

**Comment by S4MT3K** [comment]
And Don’t forget to wipe the server that the loot can spawn properly.
