### ISSUE TITLE
Admin command crash server

### ISSUE THREAD

**Issue by BorizzK** [Da0ne/DZMods#13]
AdminTool.c (solo)

If login as admin and send command /tpdds, /tpsts or other not correct commands in to chat, server crash in function CheckCommand()
(Checked by logging)
In this case, no errors are writing to log, only minidump is created.

Code with extended logging

```
   ref array<string> CheckCommand(string CommandLine)
    {
    	ref array<string> ret = new array<string>;
    	string strRplce, mKey;
    	int cmdLength;

    	strRplce = CommandLine;
		
		Print("::: AdminTools.c ::: CheckCommand ::: CommandLine: " + strRplce);

    	for (int i = 0; i < m_ExtendedCommands.Count(); ++i)
    	{
    		mKey 	  = m_ExtendedCommands.GetKey(i);
    		cmdLength = m_ExtendedCommands.Get(mKey);

			Print("::: AdminTools.c ::: CheckCommand ::: mKey: " + mKey);
			Print("::: AdminTools.c ::: CheckCommand ::: cmdLength: " + cmdLength.ToString());
			
    		if (CommandLine.Contains(mKey))
    		{
    			strRplce.Replace(mKey + " ","");
				Print("::: AdminTools.c ::: CheckCommand ::: strRplce.Replace(mKey + ' ',''): " + mKey);
				
    			ret.Insert(mKey); //0 = Command 1 = Data
				Print("::: AdminTools.c ::: CheckCommand ::: ret.Insert(mKey): " + mKey);
				
    			if (strRplce != "")
    			{
    				ret.Insert(strRplce);
					Print("::: AdminTools.c ::: CheckCommand ::: ret.Insert(strRplce): " + strRplce);
    			}

    		}
    	}
    	return ret;
    }

```
part of script.log:

SCRIPT       : ::: AdminTools.c ::: CheckCommand ::: CommandLine: /tpdds
SCRIPT       : ::: AdminTools.c ::: CheckCommand ::: mKey: /strip
SCRIPT       : ::: AdminTools.c ::: CheckCommand ::: cmdLength: 6
SCRIPT       : ::: AdminTools.c ::: CheckCommand ::: mKey: /kill
SCRIPT       : ::: AdminTools.c ::: CheckCommand ::: cmdLength: 1
SCRIPT       : ::: AdminTools.c ::: CheckCommand ::: mKey: /tpto
SCRIPT       : ::: AdminTools.c ::: CheckCommand ::: cmdLength: 5
SCRIPT       : ::: AdminTools.c ::: CheckCommand ::: mKey: /tpp
SCRIPT       : ::: AdminTools.c ::: CheckCommand ::: cmdLength: 4
SCRIPT       : ::: AdminTools.c ::: CheckCommand ::: mKey: /godmode
SCRIPT       : ::: AdminTools.c ::: CheckCommand ::: cmdLength: 1
SCRIPT       : ::: AdminTools.c ::: CheckCommand ::: mKey: /daytime
SCRIPT       : ::: AdminTools.c ::: CheckCommand ::: cmdLength: 1
SCRIPT       : ::: AdminTools.c ::: CheckCommand ::: mKey: /ammo
SCRIPT       : ::: AdminTools.c ::: CheckCommand ::: cmdLength: 1
SCRIPT       : ::: AdminTools.c ::: CheckCommand ::: mKey: /debug
SCRIPT       : ::: AdminTools.c ::: CheckCommand ::: cmdLength: 1
SCRIPT       : ::: AdminTools.c ::: CheckCommand ::: mKey: /nighttime
SCRIPT       : ::: AdminTools.c ::: CheckCommand ::: cmdLength: 1
SCRIPT       : ::: AdminTools.c ::: CheckCommand ::: mKey: /heal
SCRIPT       : ::: AdminTools.c ::: CheckCommand ::: cmdLength: 1
SCRIPT       : ::: AdminTools.c ::: CheckCommand ::: mKey: /export
SCRIPT       : ::: AdminTools.c ::: CheckCommand ::: cmdLength: 1
SCRIPT       : ::: AdminTools.c ::: CheckCommand ::: mKey: /tpalltome
SCRIPT       : ::: AdminTools.c ::: CheckCommand ::: cmdLength: 1
SCRIPT       : ::: AdminTools.c ::: CheckCommand ::: mKey: /stamina
SCRIPT       : ::: AdminTools.c ::: CheckCommand ::: cmdLength: 1
SCRIPT       : ::: AdminTools.c ::: CheckCommand ::: mKey: /spg
SCRIPT       : ::: AdminTools.c ::: CheckCommand ::: cmdLength: 4
SCRIPT       : ::: AdminTools.c ::: CheckCommand ::: mKey: /spi
SCRIPT       : ::: AdminTools.c ::: CheckCommand ::: cmdLength: 4
SCRIPT       : ::: AdminTools.c ::: CheckCommand ::: mKey: /spawncar
SCRIPT       : ::: AdminTools.c ::: CheckCommand ::: cmdLength: 1
SCRIPT       : ::: AdminTools.c ::: CheckCommand ::: mKey: /killall
SCRIPT       : ::: AdminTools.c ::: CheckCommand ::: cmdLength: 1
SCRIPT       : ::: AdminTools.c ::: CheckCommand ::: mKey: /tppm
SCRIPT       : ::: AdminTools.c ::: CheckCommand ::: cmdLength: 5
SCRIPT       : ::: AdminTools.c ::: CheckCommand ::: mKey: /CustomLoadouts
SCRIPT       : ::: AdminTools.c ::: CheckCommand ::: cmdLength: 1
SCRIPT       : ::: AdminTools.c ::: CheckCommand ::: mKey: /freecam
SCRIPT       : ::: AdminTools.c ::: CheckCommand ::: cmdLength: 1
SCRIPT       : ::: AdminTools.c ::: CheckCommand ::: mKey: /updateLoadouts
SCRIPT       : ::: AdminTools.c ::: CheckCommand ::: cmdLength: 1
SCRIPT       : ::: AdminTools.c ::: CheckCommand ::: mKey: /tpc
SCRIPT       : ::: AdminTools.c ::: CheckCommand ::: cmdLength: 4
SCRIPT       : ::: AdminTools.c ::: CheckCommand ::: mKey: /SpawnArmed
SCRIPT       : ::: AdminTools.c ::: CheckCommand ::: cmdLength: 1
SCRIPT       : ::: AdminTools.c ::: CheckCommand ::: mKey: /LoadoutType
SCRIPT       : ::: AdminTools.c ::: CheckCommand ::: cmdLength: 1
---->SERVER CRASH HERE

**Comment by Da0ne** [comment]
Thanks for the feedback, your admintool.c does not match the latest version on the gitpost, I will fix the issue.

**Comment by Da0ne** [comment]
Just updated it, should fix the issue. I tested it with the wrong commands such as: **/tpdds, /tpsts** and it did not crash.
