### ISSUE TITLE
Spawn Loadout gender

### ISSUE THREAD

**Issue by RealShu** [Da0ne/DZMods#131]
I have made the custom preset loadouts. But im curious about the genders. Can you not pick different characters? along with when i spawn as a chick i spawn with nothing from the loadouts

**Comment by Peinful** [comment]
Reason for you spawning with nothing in is due to the clothing having Female models. Meaning they need to add the female models to the spawning loadouts.

**Comment by Da0ne** [comment]
No thats not the issue @Peinful, sometimes the loadout does not get loaded properly and never spawns in. It is not due to the character being a different gender.
