### ISSUE TITLE
getting kicked off server due to modified data

### ISSUE THREAD

**Issue by smashead86** [Da0ne/DZMods#132]
So its kicking me off saying that I have modified date, i'm assuming its not compatable with the server's data I set up. 

not really sure where to proceed from here, as far as I know everything is set up right. I am using community online tool, as well. could that be the issue?

**Comment by smashead86** [comment]
oh I should add, the server is definitly loading the mod files, tried to join with out the files loaded on my client, and no go

**Comment by smashead86** [comment]
![image](https://user-images.githubusercontent.com/45495593/49675185-96d30f00-fa42-11e8-83f4-beffea3946a2.png)

now im getting this error. oh lordy

**Comment by GravityWolfNotAmused** [comment]
So? What's your issue?

**Comment by Jello22** [comment]
Seeing the same issue about the modified data.

I recently setup server using the directions from github and client install the same.  Made sure both required addons are loaded.

**Comment by smashead86** [comment]
Nevermind, just got it working. Apparently COT isn't compatible.

**Comment by beals1pt0** [comment]
It will also do this if you don't get all the keys as well

**Comment by Jello22** [comment]
How many keys are their in total?  I have tried it with the bi keys plus the rpfc. Along the keys folder in root with just the one from the workshop mod.

**Comment by Jello22** [comment]
Figured it out.  Was a key issue
