### ISSUE TITLE
Help AIRDROP instal PLS

### ISSUE THREAD

**Issue by LArtDesChOiX** [Da0ne/DZMods#133]
Hi, 
I had managed to use it before putting the Vanilla ++ back,
Now I can not use!

The tutorial is super easy ... I have to create a line like his:
IF YOU HAVE A CUSTOM MISSION CONSTRUCTOR
- CustomMission: MissionServer
ref BetterAirdrop Airdrop;
- Add following to your constructor
Airdrop = new BetterAirdrop ();
=
             ref BetterAirdrop Airdrop;
void DayZSurvival ()
             Airdrop = new BetterAirdrop ();

I put it under CustomMission: MissionServer But do not work ... An idea PLEASE?

**Comment by GravityWolfNotAmused** [comment]
Not an issue

**Comment by LArtDesChOiX** [comment]
No, just need help ^^, there is no section for his...

**Comment by sy8282** [comment]
This is vanilla++ they don't do airdrops.
You need to contact whoever made your airdrops script
