### ISSUE TITLE
Custom spawns

### ISSUE THREAD

**Issue by wydox1SK** [Da0ne/DZMods#136]
Having issues creating custom spawns and displaying them on the spawn menu, since i cannot find any documentation about this issue im wondering if anyone would be able to point me in the right direction. Thanks.

**Comment by Da0ne** [comment]
To create a custom spawn point, you can either do it by adding it to the SpawPoibts.json file in your server profile OR use the in game admin command:’/savePoint nameOfPos` it will export it to that file. The cool down timer can be edited via that file. Next update will include admin tools UI, which will allow for full modification of all mods features via in game. So no messing around with code. Will make it so simple to edit your gameplay and V++ modifications. Stay tuned, working hard.
