### ISSUE TITLE
Cant compile mission init script

### ISSUE THREAD

**Issue by exm316** [Da0ne/DZMods#14]
Hello,

I have just tried to install the full DayZ Vanilla++ Mission.

Once I start the server with my Batch File the server starts but fails to fully load. I get an error message/Compile Error

_Cant compile mission init script_

_InfectedHordes.x(88): Undefined function ' AttachEventHandle'_

I have looked at line 88 in the InfectedHordes.c and it says - _Bszmb.AttachEventHandle(PossibleLootDrops,PossibleWeaponDrops,dropChance);_

Is it something that I have done wrong or an issue in the new code, as I see it was updated earlier today.

**Comment by Da0ne** [comment]
Could you please send me your whole launch param from the batch.

**Comment by exm316** [comment]
-config=Survivalserver\serverDZ.cfg -mod=ModdedScripts -profiles=Servivalserver -name=Test -port=2302 -dologs -adminlog -netlog -noFilePatching -BEpath=C:\Server\Battleye -profiles=C:\Server\PlayerLogs -cpucount=6

**Comment by Da0ne** [comment]
>I figured out what was wrong. I had 2 _-mod_ in my start parameters. 1 for yours and 1 for another older mod that I had installed, once I removed the old one the server boots up fine. ...

@exm316 if you wish to run two mods at once; first make sure the other mod does not clash with mine. At the moment most mods clash with scripts. But if you do want to try it the command parameter will be like this: -mod=ModdedScripts;myothermod

**Comment by Bhuddaguy** [comment]
Hello Da0ne, I'm having a similar issue, however, the compile error points to ScriptedMods//Modules//ServerEvents//InfectedHordes.c(89): Undefined function 'AttachEventHandle' 
I've attached a sample of my start.bat file. Thanks again for making this mod available. I am using it on a couple of vilayer servers I run. Cheers.
[Start - Copy.txt](https://github.com/Da0ne/DZMods/files/2590839/Start.-.Copy.txt)
