### ISSUE TITLE
Server crash errors

### ISSUE THREAD

**Issue by RealShu** [Da0ne/DZMods#142]
Seem to be getting this error every crash - 

NULL pointer to instance
Class:      'SurvivorBase'
Entity id:2954666
 
Function: 'EEKilled'
Stack trace:
ModdedScripts/scripts/4_World/entities\manbase\playerbase.c:72

**Comment by chawdinky** [comment]
Looks like you are running a older version of the do you have @ModdedScripts in your run.bat command line?

**Comment by RealShu** [comment]
Still happened when I ran the updated version. No matter what I do or use always get this crash error

**Comment by chawdinky** [comment]
What does your run.bat file look like. Please insert lines

**Comment by RealShu** [comment]
Mod wise or?
