### ISSUE TITLE
Question "beginner lol"

### ISSUE THREAD

**Issue by LArtDesChOiX** [Da0ne/DZMods#143]
Vanilla ++ will always work with the arrival of the 1.0 ??
Thanks soon, great taff!

**Comment by chawdinky** [comment]
Yes it should work just fine, and if and i strongly say "IF" it does break anything, it will be getting fixed in a timely manner. Just talked with DaOne a few minutes ago about this.
https://i.gyazo.com/809ebfbddf5864196c297453426c4ea6.png

**Comment by GravityWolfNotAmused** [comment]
This is something we cannot foresee. We do not know if BI changed anything which could break our mod; regardless, if in chance it breaks VanillaPP, Da0ne and myself will continue to patch it.

**Comment by LArtDesChOiX** [comment]
Ok, we are all a bit in the unknown ^^, thanks for your answers!
Good continuation ;)
