### ISSUE TITLE
is the latest version working on 1.0 

### ISSUE THREAD

**Issue by sy8282** [Da0ne/DZMods#144]
ive been running the old version with the better building spawner but seems that is now dead as it crashes the servger on launch throws lots and lots of errors is the new version any better

**Comment by Sniy** [comment]
I think the People need the Time to find the Problem .
Good Work Bro´s .

**Comment by sy8282** [comment]
so theres a problem with the newest version aswell?
mine is the first moddedscripts serversided only just need to know if the new @vanilla is working on 1.0

**Comment by SirFrostingham** [comment]
---------------------------
Compile error
---------------------------
Can't compile mission init script'!

$CurrentDir://mpmissions//DayZSurvival.chernarusplus//ScriptedMods//Modules//ServerEvents//InfectedHordes.c(89): Undefined function 'AttachEventHandle'
---------------------------
Abort   Retry   Ignore   
---------------------------

.\mpmissions\DayZSurvival.chernarusplus\ScriptedMods\Modules\ServerEvents\InfectedHordes.c

line 90:
Bszmb.AttachEventHandle(PossibleLootDrops,PossibleWeaponDrops,dropChance);

I commented the line for now and the scripts load.

**Comment by GravityWolfNotAmused** [comment]
AttachEventHandle is defined inside of ZombieBase you can clearly see this on line 14. People always have this issue before and after the update. I fail to see how this isn't from failure to install correctly?

**Comment by sy8282** [comment]
i dunno man was working fine i updated to 1.0 and it wouldnt compile commented out the line and then got another error inside world\entities\playerbase.c(154) something about NULL

**Comment by GravityWolfNotAmused** [comment]
That's the error that I am working on right now

**Comment by chawdinky** [comment]
Can't compile mission init script'!
 
$CurrentDir://mpmissions//DayZSurvival.chernarusplus//ScriptedMods//Modules//AdvancedLoadouts//AdvancedLoadouts.c(83): Unknown type 'CallType'

**Comment by GravityWolfNotAmused** [comment]
@chawdinky I think this is caused by not updating RPCManager w/ key.

**Comment by HumnResources** [comment]
GravityWolf. In the update patch notes there was changes to the commands in launch params. I managed to get it working (though didn't connect just server start) by REMOVING "-scrAllowFileWrite" and REPLACING that with "-filePatching"

**Comment by HumnResources** [comment]
Update:

The error code I am now receiving is the same as sy8282;

VanillaPP/scripts/4_World/entities\manbase\playerbase.c(159): Only NULL assignment is allowed.

**Comment by sy8282** [comment]
so ive been reading online that the 1.0 update has made mod.cpp redundant in its current format and should be packed as a config.cpp inside the pbo 
taken from this in the patchnotes 
Changed: The content of the mod.cpp must be included into the mod configuration
and a discussion with a guy that knows a little more than me 
not sure if that helps getting towards a solution or not

**Comment by chawdinky** [comment]
> @chawdinky I think this is caused by not updating RPCManager w/ key.

Yeah, figured. i have had 0 sleep today. Thanks mate!

**Comment by sy8282** [comment]
just a heads up i remove the bleeding computation on line 154 as its only for safezone function and server started just no hordes or safezone 

but admintools are working fine

**Comment by Killtacular** [comment]
Updated to 1.0 then restart the server and everything seems to be normal.
No crashes, no compile errors.

**Comment by chawdinky** [comment]
> That's the error that I am working on right now

Yeah, same error // it out for now

**Comment by ChronicGamer420** [comment]
is there any reason why the admin codes arent working, like spawning in items and teleporting nothing seems to be working even after i login and my guid is there in admin file

**Comment by HumnResources** [comment]
> is there any reason why the admin codes arent working, like spawning in items and teleporting nothing seems to be working even after i login and my guid is there in admin file

Try checking the admins.txt for an empty line/remove it. And double check its your uid and not the standard one provided.

**Comment by ChronicGamer420** [comment]
yip done that, altho vanilla plus plus doesnt like to work lol so im not using rpc or ++ atm

**Comment by ChronicGamer420** [comment]
yea, tried everything and no works

**Comment by HumnResources** [comment]
Just to provide an update;

I managed to get it working and such by commenting out the godmode for safe area, as stated above. 
So far working confirmed; 
Advanced Loadouts; Custom menu/random/loadouts incl spawn armed. --working. 
Admin commands --working
Zombie Horde --working

The above are all i use on my server so it seems fully functional in my use case. I do not have Custom buildings or safezone enabled.

Hope this can help ! Best of luck and thank you again for all your hard work!

**Comment by Da0ne** [comment]
The mod is seriously fucked tbh, all the serialization of the Json and loadout data...spawn points etc.. its all broken due to the devs. I cant do ANYTHING about it i have to wait for their fix. I have fixed all the issues with startup and errors due to outdated code (0.63-1.0). But the main issue is to do with core engine functions that i rely on to read write and make data. I appreciate everyone who is active here and trying to help out :)

**Comment by HumnResources** [comment]
It'll be done ! Don't fret, do what you can for now that's all. Appreciate the updates.

 I'm not quite free right now however, if you would like me to test anything let me know! So far the only bug i have run into is; unconscious respawning. If the character is unconscious, and i respawn. I have to relog. However, other than that. I have been having little to no issues. Hordes spawn okay, inventory spawns on character load etc. I can test the safezone feature later tonight if you havent figured things out by then. 

Glad to help wherever needed! Best of luck!

**Comment by Da0ne** [comment]
@HumnResources Can you send me a picture of your Json file in your profile " SpawnPoints.json " also a if possible a dump of the script.log from server start

**Comment by HumnResources** [comment]
[script.log](https://github.com/Da0ne/DZMods/files/2680503/script.log)
![capture](https://user-images.githubusercontent.com/45860646/50010276-f66f7400-ff86-11e8-8211-551a3a473945.PNG)

There you go sir, both as per requested. I am leaving my house however and wont be able to reply so i do hope that helps! 

As for the respawn points, i did copy over the json respawn file i had from a backup. As when i first launched the server it was "replaced" with an empty one.

**Comment by Da0ne** [comment]
Yup, thats the issue "the empty one" its supposed to fill out default points but due to max cap they added 18kb is too much lol. Thanks for that.

**Comment by HumnResources** [comment]
Saw this before I ran out. Noted, I will see if I can test and try to get the static loadouts to work tonight after work. Again, if you haven't figured something out by then. Keeping in mind I unfortunately know next to nothing about code, let alone enscript.

I never tried the static loadouts, only random/itemized selection. Maybe it can be resolved the same way as the spawn points. May be able to just write a separate json outside of the game for it I'm sure. Maybe you can just bundle the .json in with the downloads for the time being? Either way, I'm glad my insomniac night came out to some usefulness haha. (Had a lot of fun getting it to work though ;p) 

Good luck with your tasks throughout the day! I'll check back here for any updates when i have the time.

**Comment by LArtDesChOiX** [comment]
I try to install Vanilla++.. Dont work you need do a maj ? Good luck

**Comment by GravityWolfNotAmused** [comment]
@HumnResources Can you send me your json file?
