### ISSUE TITLE
Player with network id 0 not found - when logging in

### ISSUE THREAD

**Issue by jesst3r** [Da0ne/DZMods#146]
[http://prntscr.com/lvlejo](url)
Greetings, encountered problem, any ideas how to fix it? Thanks in advance

`14:19:32 [StateMachine]: Player Survivor (dpnid 95348367 uid Yx6LiQkVZAqu6ZvRf3+jtDYFHK9ZYqlyt5lRnZCmzGw=) Entering GetCharacterLoginState
14:19:32 [StateMachine]: Player Survivor (dpnid 95348367 uid Yx6LiQkVZAqu6ZvRf3+jtDYFHK9ZYqlyt5lRnZCmzGw=) Entering CreateNetObjectsLoginState
14:19:32 Player Survivor dpid=95348367 at pos (13470.4, 0.0, 5644.2) 
14:19:32 [StateMachine]: Player Survivor (dpnid 95348367 uid Yx6LiQkVZAqu6ZvRf3+jtDYFHK9ZYqlyt5lRnZCmzGw=) Entering PreloadCamLoginState
14:19:32 [StateMachine]: Player Survivor (dpnid 95348367 uid Yx6LiQkVZAqu6ZvRf3+jtDYFHK9ZYqlyt5lRnZCmzGw=) Entering WaitPreloadCamLoginState
14:19:47 [StateMachine]: Player Survivor (dpnid 95348367 uid Yx6LiQkVZAqu6ZvRf3+jtDYFHK9ZYqlyt5lRnZCmzGw=) Entering GetNewCharLoginState
14:19:47 [StateMachine]: Player Survivor (dpnid 95348367 uid Yx6LiQkVZAqu6ZvRf3+jtDYFHK9ZYqlyt5lRnZCmzGw=) State Error (GetNewCharLoginState): Player with network id 0 not found
14:19:47 Player Survivor (95348367) kicked from server: 6 ()
14:19:47 [StateMachine]: Kick player Survivor (dpnid 95348367 uid Yx6LiQkVZAqu6ZvRf3+jtDYFHK9ZYqlyt5lRnZCmzGw=) State GetNewCharLoginState Error `

**Comment by BraydenGirard** [comment]
I am also having this problem, I have used the server before adding the mod and all was good with players connecting. I followed instructions to setup mod but have not changed any default settings. Is there something that needs to be opened up to allow people to connect?

**Comment by c4timah** [comment]
> 
> 
> I am also having this problem, I have used the server before adding the mod and all was good with players connecting. I followed instructions to setup mod but have not changed any default settings. Is there something that needs to be opened up to allow people to connect?

They need to launch use the DayZ Launcher option from Steam. They don't have the workshop items needed to play on the server. I was having the exact same issue until I had players subscribe to vanilla++, rpcframework and permissionsframework. After that, no issues. But players need to launch the game in steam with the DayZ Launcher so they can enable and load the mods for the server.
<img width="287" alt="dayzlauncher" src="https://user-images.githubusercontent.com/45471284/50555050-3d01e580-0c8c-11e9-9f98-ea90a650c8ce.PNG">

**Comment by Doud0u** [comment]
Hello,
Same problem with me too.

[crash.log](https://github.com/Da0ne/DZMods/files/2776722/crash.log)
[script.log](https://github.com/Da0ne/DZMods/files/2776723/script.log)
[DayZServer_x64_2019-01-20_15-51-43.log](https://github.com/Da0ne/DZMods/files/2776724/DayZServer_x64_2019-01-20_15-51-43.log)
