### ISSUE TITLE
how to moded dayz server?

### ISSUE THREAD

**Issue by AndyLee1024** [Da0ne/DZMods#152]
I want to create a mod  use for servers (eg: no stamina). can u give me a tutorial or documention? thank you.

**Comment by beals1pt0** [comment]
Its already in this mod ready the read.me

**Comment by beals1pt0** [comment]
> I want to create a mod use for servers (eg: no stamina). can u give me a tutorial or documention? thank you.

Its already in this mod ready the read.me
