### ISSUE TITLE
issue adding ammo

### ISSUE THREAD

**Issue by Yarpii-Tech** [Da0ne/DZMods#154]
hi there... well i just added the mod today to the server.... but got some problems with using the tool
i have tried to add the ammo to myself but some times it works but most of the time it does not...

and the command i tried are:
/ammo 
/ammo user

So i was wondering if i do something wrong or its a think other also encounter

**Comment by S4MT3K** [comment]
The problem is the spelling. The system detects the word ammo and want to execute the code :ammo.
When you use ammo user it wont work.
At first: Don’t use spaces.

My suggestion for your two commands.

/myammo or /adminammo
/userammo
