### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by Irkutsk38** [Da0ne/DZMods#155]
Hi. I have on a betrays such a mistake. Perhaps because of the mod @ZomBerry Admin Tools

---------------------------------------------
Log C:\DayZServer_2\ServerProfilesFolder\crash.log started at 22.12. 07:39:07
------------------------------------
SRV82045, 22.12 2018 08:00:30
NULL pointer to instance
Class:      'SurvivorBase'
Entity id:0

Function: 'Init'
Stack trace:
scripts/4_World/entities\manbase\playerbase.c:200
scripts/4_World/entities\manbase\playerbase.c:173
$CurrentDir://mpmissions//DayZSurvival.chernarusplus//ScriptedMods//Modules//AdvancedLoadouts//AdvancedLoadouts.c:220
$CurrentDir://mpmissions//DayZSurvival.chernarusplus//ScriptedMods//Modules//AdvancedLoadouts//AdvancedLoadouts.c:79
$CurrentDir://mpmissions//DayZSurvival.chernarusplus//ScriptedMods//Modules//ServerMission//DayZSurvival.c:57
$CurrentDir://mpmissions//DayZSurvival.chernarusplus//ScriptedMods//Modules//ServerMission//DayZSurvival.c:36
$CurrentDir:mpmissions\DayZSurvival.chernarusplus\init.c:5

Runtime mode
CLI params: port 2402 config ServerProfilesFolder\serverDZ.cfg cfg ServerProfilesFolder\basic.cfg profiles ServerProfilesFolder dologs  adminlog  freezecheck  scriptDebug true mod @RPCFramework;@ZomBerry Admin Tools;@Trader;@VanillaPlusPlus;@DisableBaseDestruction;@InventoryPlus;@[MOV] Airdrop Redux;@[MOV] Notification Framework;@DayZ_CCCP;@SQUAD MSF-C 

------------------------------------
SRV82045, 22.12 2018 08:00:30
NULL pointer to instance
Class:      'Environment'
Function: 'Init'
Stack trace:
scripts/4_World/classes\environment\environment.c:72
scripts/4_World/classes\environment\environment.c:55
scripts/4_World/entities\manbase\playerbase.c:218
scripts/4_World/entities\manbase\playerbase.c:173
$CurrentDir://mpmissions//DayZSurvival.chernarusplus//ScriptedMods//Modules//AdvancedLoadouts//AdvancedLoadouts.c:220
$CurrentDir://mpmissions//DayZSurvival.chernarusplus//ScriptedMods//Modules//AdvancedLoadouts//AdvancedLoadouts.c:79
$CurrentDir://mpmissions//DayZSurvival.chernarusplus//ScriptedMods//Modules//ServerMission//DayZSurvival.c:57
$CurrentDir://mpmissions//DayZSurvival.chernarusplus//ScriptedMods//Modules//ServerMission//DayZSurvival.c:36
$CurrentDir:mpmissions\DayZSurvival.chernarusplus\init.c:5

Runtime mode
CLI params: port 2402 config ServerProfilesFolder\serverDZ.cfg cfg ServerProfilesFolder\basic.cfg profiles ServerProfilesFolder dologs  adminlog  freezecheck  scriptDebug true mod @RPCFramework;@ZomBerry Admin Tools;@Trader;@VanillaPlusPlus;@DisableBaseDestruction;@InventoryPlus;@[MOV] Airdrop Redux;@[MOV] Notification Framework;@DayZ_CCCP;@SQUAD MSF-C 

------------------------------------
SRV82045, 22.12 2018 08:00:43
NULL pointer to instance
Class:      'InfectedHordes'
Function: 'SpawnHorde'
Stack trace:
$CurrentDir://mpmissions//DayZSurvival.chernarusplus//ScriptedMods//Modules//ServerEvents//InfectedHordes.c:90
$CurrentDir://mpmissions//DayZSurvival.chernarusplus//ScriptedMods//Modules//ServerEvents//InfectedHordes.c:50
$CurrentDir://mpmissions//DayZSurvival.chernarusplus//ScriptedMods//Modules//ServerMission//DayZSurvival.c:129

Runtime mode
CLI params: port 2402 config ServerProfilesFolder\serverDZ.cfg cfg ServerProfilesFolder\basic.cfg profiles ServerProfilesFolder dologs  adminlog  freezecheck  scriptDebug true mod @RPCFramework;@ZomBerry Admin Tools;@Trader;@VanillaPlusPlus;@DisableBaseDestruction;@InventoryPlus;@[MOV] Airdrop Redux;@[MOV] Notification Framework;@DayZ_CCCP;@SQUAD MSF-C 

------------------------------------
SRV82045, 22.12 2018 08:00:43
NULL pointer to instance
Class:      'InfectedHordes'
Function: 'SpawnHorde'
Stack trace:
$CurrentDir://mpmissions//DayZSurvival.chernarusplus//ScriptedMods//Modules//ServerEvents//InfectedHordes.c:90
$CurrentDir://mpmissions//DayZSurvival.chernarusplus//ScriptedMods//Modules//ServerEvents//InfectedHordes.c:50
$CurrentDir://mpmissions//DayZSurvival.chernarusplus//ScriptedMods//Modules//ServerMission//DayZSurvival.c:129

Runtime mode
CLI params: port 2402 config ServerProfilesFolder\serverDZ.cfg cfg ServerProfilesFolder\basic.cfg profiles ServerProfilesFolder dologs  adminlog  freezecheck  scriptDebug true mod @RPCFramework;@ZomBerry Admin Tools;@Trader;@VanillaPlusPlus;@DisableBaseDestruction;@InventoryPlus;@[MOV] Airdrop Redux;@[MOV] Notification Framework;@DayZ_CCCP;@SQUAD MSF-C 

------------------------------------
SRV82045, 22.12 2018 08:00:43
NULL pointer to instance
Class:      'InfectedHordes'
Function: 'SpawnHorde'
Stack trace:
$CurrentDir://mpmissions//DayZSurvival.chernarusplus//ScriptedMods//Modules//ServerEvents//InfectedHordes.c:90
$CurrentDir://mpmissions//DayZSurvival.chernarusplus//ScriptedMods//Modules//ServerEvents//InfectedHordes.c:50
$CurrentDir://mpmissions//DayZSurvival.chernarusplus//ScriptedMods//Modules//ServerMission//DayZSurvival.c:129

Runtime mode
CLI params: port 2402 config ServerProfilesFolder\serverDZ.cfg cfg ServerProfilesFolder\basic.cfg profiles ServerProfilesFolder dologs  adminlog  freezecheck  scriptDebug true mod @RPCFramework;@ZomBerry Admin Tools;@Trader;@VanillaPlusPlus;@DisableBaseDestruction;@InventoryPlus;@[MOV] Airdrop Redux;@[MOV] Notification Framework;@DayZ_CCCP;@SQUAD MSF-C

**Comment by Moondarker** [comment]
ZomBerry is not even in stack trace, so it's not ZomBerry's fault  /._.

@Da0ne, about last 3 entries, add a check if zombie was actually spawned after
`EntityAI AIzmb = GetGame().CreateObject( zmbClass, pos, false, true );`
Seems like CreateObject sometimes returns null for no obvious reasons, seen this issue before

**Comment by S4MT3K** [comment]
I think this issue is caused by the tick. I had the issue that the first killed Zed Crashes my Server. It executed the Code but instantly crashes though. I never fixed it. Its just gone 🤷🏼‍♂️

But the Print i made stopped directly after The getrandomloot and then crashes. Maybe daone can take look?!? 

If anybody need more infos i can try to force this crash and post a logfile.
