### ISSUE TITLE
crashing server

### ISSUE THREAD

**Issue by thevault8** [Da0ne/DZMods#156]
seeing these errors today on RPT. Worked fine yesterday.
9:42:39 SCRIPT (W): @"scripts/5_Mission/gui\inventorynew\inherited\playercontainer.c,754": Unsafe down-casting, use 'Container.Cast' for safe down-casting

9:42:39 SCRIPT (W): @"VanillaPP/scripts/5_Mission/gui\vppspawnmenu.c,841": Unsafe down-casting, use 'EntityAI.Cast' for safe down-casting

9:42:39 SCRIPT (W): @"VanillaPP/scripts/5_Mission/gui\vppspawnmenu.c,861": Unsafe down-casting, use 'EntityAI.Cast' for safe down-casting

9:42:39 SCRIPT (W): @"VanillaPP/scripts/5_Mission/gui\vppspawnmenu.c,881": Unsafe down-casting, use 'EntityAI.Cast' for safe down-casting

**Comment by Moondarker** [comment]
These are warnings tho, and your server doesn't seem to crash

**Comment by GravityWolfNotAmused** [comment]
This has to do with BI, and DaOne and myself not using the proper way of down casting variables into inherited types. I'll do a check before we push our next update. They shouldn't cause any huge issues for you.
