### ISSUE TITLE
able to install with own mission file?

### ISSUE THREAD

**Issue by robbhimself** [Da0ne/DZMods#157]
is there a list of which files in the mission folder that are modified?

I already have my own heavily modified mission file and i'd like to use that and make the edits necessary.

It looks like its just the ScriptedMods folder and the code in init.c? I just want to make sure

thanks

**Comment by Da0ne** [comment]
Nah, you are gonna have to use the whole mission. If you want to use the mod you use it as is. I’m sorry I can’t help you to get it working with your own. That requires lots of work and changes.
