### ISSUE TITLE
MOTD Only Random/White/Pink?

### ISSUE THREAD

**Issue by S4MT3K** [Da0ne/DZMods#16]
Hey i have a Problem. Again :P How to set up other colors for Chatmessages? I figured out that you can put a 1 instead of 5 (GetGame().ChatPlayer(1, Messages...........) then it is Pink, Other numbers dont work. I know this is for something else :P but for what exactly  i dont know. Is there a way to colorize them? 

Other Thing, and this is the biggest Problem for now, is the randomizing of the messages. I tried to change the code that it will work without randominzing, but in every build i made it has some array issues. So is there a way to show the messages e.g.: "Welcome to our server", "No KOS", "Server Restarts every 6 hours", "No tents in military bases", "Vivit us on Facebook", in a loop? Cause with your code it shows me sometimes 5 times the same message. Thanks for help.
Greetz S4MT3K

**Comment by Da0ne** [comment]
Right thanks for the feedback, as for the chat messages you can only do two colors. White or Pink. I cant change that unless i mod the client as well.

As for the MOTD, i will write an option that you can enable/disable randomized messages and make it use the messages in correct order. 👍

**Comment by S4MT3K** [comment]
Okay, THANK YOU VERY MUCH... I Love your Work... Cant wait for it :D 
One last suggestion: Can you implement a option for sheduled outputs like in the Extended Battleeye Client!

**Comment by robotstar78** [comment]
@S4MT3K Did you manage to get Godmode working with your code amends? If you did I'd definitely be interested to know how!

**Comment by S4MT3K** [comment]
> 
> 
> @S4MT3K Did you manage to get Godmode working with your code amends? If you did I'd definitely be interested to know how!

to Keep the issue discussion clean here, please send me a message over our website under KONTAKT. I´ll explain you how i managed this. Website: www.bbgamingclan.de

**Comment by S4MT3K** [comment]
> 
> 
> Would be great if you could also disable the messages in settings.c as when I delete the contents of the message and leave the “” it still says “SC:” with a blank message.
> 
> Would be great also if you can remove the “SC:” before every message.

You tried to start your server with an blank name? 

start DayZServerx64.exe -name -nologs..........

Or just comment the whole funtion out!

You can also, if youre good in programming write your onn boolean cindition.
