### ISSUE TITLE
Kicked off servers from modified data

### ISSUE THREAD

**Issue by rori56** [Da0ne/DZMods#160]
Hello,

I installed the Vanilla++ and the RPC mod from the workshop, and when i'm trying to join any modded servers, it kick me off and appears a error message 
"Kicked off the game. (Modified data: steamapps\Dayz\!Workshop\(Vanilla++ or RPC)....

I tried to copy all the bikeys from mods, and paste them to a created Keys folders; steamapps/Days/Keys
Didn't work.

**Comment by chawdinky** [comment]
Give me your start.bat commandline

**Comment by chawdinky** [comment]
Screenshot your server folder

**Comment by rori56** [comment]
the fact is, im not trying to install it on a server, but on my client, i'm just trying to join modded server from others.

**Comment by rori56** [comment]
Nevermind, idk how, it's solved

**Comment by GravityWolfNotAmused** [comment]
It's because they
