### ISSUE TITLE
Admin Commands Do Not Work

### ISSUE THREAD

**Issue by c4timah** [Da0ne/DZMods#162]
While in game:
1. Press [ ?/ ] key
2. Enter: #longin MyPassWord
3. Server Confirmation:  c4timah logged in as admin
4. Press [ ?/ ] key again, press enter: /heal
5. Server returns message c4timah: /heal

I have run through all the admin commands. The only thing that seems to work is that it confirms that I have logged in as admin. None of the admin commands work. None. I have gone through the whole list. When typing in the commands after logging in as admin, the commands show in chat for everyone to see in the chat system. If the command works, not only should i be able to spawn items and teleport, these commands should not show in chat for all players to see. Ideas?

**Comment by Da0ne** [comment]
Did you add your Steam64 ID to the file Admins.txt?

**Comment by c4timah** [comment]
Would I get the confirmation that I logged in as admin? Its says I logged in as admin. And yes, my Steam64 ID is in the .txt file.

**Comment by cammygames** [comment]
I had the same issue. My Id was in the .txt file but it wasn't adding me. I assumed it was due to the current file bug and just commented out the file loading code and replaced it with just the insert to the array line.

**Comment by c4timah** [comment]
I’m not a coder so you’ve lost me already. I’ve dabbled with mods in arma3 but could use an example to understand what it is your getting at when you say, “just commented out the file loading code and replaced it with just the insert to the array line.” I would know where to begin to make that happen or the name of the file to modify.

**Comment by cammygames** [comment]
in DayZSurvival.chernarusplus/ScriptedMods/Modules/AdminTool/AdminTool.c
https://i.imgur.com/sg5vFrE.png

Then i added this below m_AdminList.Insert("MY STEAM ID","null"); //UID , NAME

**Comment by Da0ne** [comment]
No reason to do that, it works fine. You probably had a space left after the UID or a line break somewhere.

**Comment by c4timah** [comment]
Double checked, there are no spaced, SteamID64 is correct, re-verified that at steamid.io. The above option gives me the same results. I can login as Admin, and the server shows "C4-timah logged in as admin" but the commands just show as chat from me with no results.

**Comment by arniegames4u** [comment]
@c4timah do you have a profile name setup?

**Comment by c4timah** [comment]
I uninstalled the mod and then reinstalled. Why that fixed the problem, we'll most likely never know. I'm assuming one of the micro updates for DayZ broke the mod somehow. It's working just fine now.
