### ISSUE TITLE
Extended Admin Commands?

### ISSUE THREAD

**Issue by c4timah** [Da0ne/DZMods#163]
Has anyone been able to add to/take away from the admin commands? I noticed some items do not spawn, like jerrycans or surpressors or even USG-45. Is there a way to add custom items? Or heal/repair vehicles?

Thanks.

**Comment by Da0ne** [comment]
What? Check: [This](https://github.com/Da0ne/DZMods/tree/master/mpmissions/DayZSurvival.chernarusplus/ScriptedMods/Modules/AdminTool)

**Comment by c4timah** [comment]
You just love closing any ticket you fin

> 
> 
> What? Check: [This](https://github.com/Da0ne/DZMods/tree/master/mpmissions/DayZSurvival.chernarusplus/ScriptedMods/Modules/AdminTool)

What part didn't make sense? I'm aware of the readme, it merely doesn't cover the item names that it can spawn. Outside the two examples in the readme, I was wondering if there was a "list" of items we can call up using /spi or /spg. For example, /spg jerrycan does not produce anything. Is it called up by another name? And FFS! Do you have to close everything that you feel isn't worth your time??? Someone from the community could have possibly provided a worth while tip that you apparently feel is below you.

**Comment by arniegames4u** [comment]
C4timah...I say this in attempt to preserve Da0ne’s mental stability. You need to chill out. Your question about spawning items in is completely common knowledge and you should try and seek answers rather than forcing answers from content creators. Please refrain from speaking to modders and content creators like this (and absolutely do not do this in a public capacity) as it keeps people from sharing and servicing our community. Please be respectful and check your tone when seeking help.

Here’s a fairly comprehensive dump of every item classname sorted for your convenience...found at the top of a google search for “dayz standalone classnames”

https://github.com/ravmustang/DayZ_SA_ClassName_Dump/tree/master

**Comment by c4timah** [comment]
> 
> 
> C4timah...I say this in attempt to preserve Da0ne’s mental stability. You need to chill out. Your question about spawning items in is completely common knowledge and you should try and seek answers rather than forcing answers from content creators. Please refrain from speaking to modders and content creators like this (and absolutely do not do this in a public capacity) as it keeps people from sharing and servicing our community. Please be respectful and check your tone when seeking help.
> 
> Here’s a fairly comprehensive dump of every item classname sorted for your convenience...found at the top of a google search for “dayz standalone classnames”
> 
> https://github.com/ravmustang/DayZ_SA_ClassName_Dump/tree/master

Thanks for the reply. I've been thru that tree over a week ago, hence my posting here. For example, the suppressor for the mp5 and ump45 is called up by /spi pistolsuppressor. It's not called up by the classname.  

I never meant any disrespect nor deliberately laced my posts with a "tone". I don't like posting these non-critical questions here but there is no help anywhere else. I was forced to "seek" answers here. And since I am not a coder of any kind I guess my questions came across as forcing answers from the content creators as you put it. Two posts were closed abruptly and his reply did not address my question in any way.  From my viewpoint, they were closed with no resolution. I got the impression he was irritated by the posts. If there is a forum somewhere in relation to Da0ne's mod, please share! I don't want to be bothersome with my questions. My sincere apologies to both him and the community here. His mod is fantastic and one of the least troublesome by far.

**Comment by GravityWolfNotAmused** [comment]
We simply are not here to provide item names. This could be an endless task with more and more items being added to the workshop. Please understand that DaOne and I are very busy with life, and the next update. We do have a discord if you ever wish to ask others questions. We try to keep issues for actual bugs, and feature requests.

**Comment by c4timah** [comment]
> 
> 
> We simply are not here to provide item names. This could be an endless task with more and more items being added to the workshop. Please understand that DaOne and I are very busy with life, and the next update. We do have a discord if you ever wish to ask others questions. We try to keep issues for actual bugs, and feature requests.

Thank you for the reply. I will definitely limit future posts to what github was designed for going forward.
