### ISSUE TITLE
Odd server crash that cropped up unexpectedly.

### ISSUE THREAD

**Issue by lordkabal26** [Da0ne/DZMods#164]
Attaching the RPT log (I manually fixed the missing semicolon on line 258 of AdminTool.c)

[DayZServer_x64_65453_2019-01-02_00-16-15.txt](https://github.com/Da0ne/DZMods/files/2719713/DayZServer_x64_65453_2019-01-02_00-16-15.txt)

**Comment by lordkabal26** [comment]
New RPT on a Vilayer server on a fresh install with only RPCFramework and VanillaPlusPlus. There's definitely something broken for it to cause the server to crash with no other mods running on a fresh server reinstall using the vilayer install method.

[DayZServer_x64_65453_2019-01-07_06-05-21.txt](https://github.com/Da0ne/DZMods/files/2731450/DayZServer_x64_65453_2019-01-07_06-05-21.txt)

**Comment by S4MT3K** [comment]
-dologs is just logging everything.
Try -nologs if the server is running good you will still have crashlog and scriptlog .txt files where you can see whats going on.
