### ISSUE TITLE
Create a MOD hordes, separate, on the workshop ??

### ISSUE THREAD

**Issue by LArtDesChOiX** [Da0ne/DZMods#165]
Hi, I think that creating a MOD Hordes separating from Vanilla, on the workshop, would be the ideal friend !!!!
It would help a lot of server, not wanting especially vanilla full!

Thank you

**Comment by Ondra97** [comment]
https://github.com/VanillaPlusPlus/InfectedHordesPlus

**Comment by GravityWolfNotAmused** [comment]
@Ondra97 You are a god, thank you.

**Comment by GravityWolfNotAmused** [comment]
@LArtDesChOiX I made it completely server side, so you can make changes and your community can build more on top of it.
