### ISSUE TITLE
How to get current freedebugcamera position?

### ISSUE THREAD

**Issue by BorizzK** [Da0ne/DZMods#17]
How to get current freedebugcamera position before player disconnect from camera and connect to entity?
GetGame().GetCurrentCameraPosition() not work (((
I try to teleport admin to current freedebugcamera position...

ThX

**Comment by Da0ne** [comment]
This is not possible due to camera script being heavily client sided, so unfortunately you can’t get the cams position. Wait for next update I will have client support.
