### ISSUE TITLE
Location of Settings.c

### ISSUE THREAD

**Issue by exm316** [Da0ne/DZMods#18]
I would like to possibly change up the code for the player announcer and also remove the how many players are on the server messages - I'm guessing this is in the settings.c from what is posted in the instructions? But can not find it anywhere! Can you point me in the right direction

_-Enable/Disable player Join/leave messages. Check the file "Settings.C"_

Cheers for everything 
EXM

**Comment by zalexki** [comment]
Pro github tip: Press T when on homepage of this repo and start typing 'settin'.
Only one file with setting in the name. :)

**Comment by Da0ne** [comment]
Thanks zalexki, @exm316 the option to enable disable the player count is not implemented, however if you wish to disable it check the script DayzSurvival.c within the function OnInit() there is a call function loop that you can comment out and turn off or remove. I will include an option to disable in the next update.

**Comment by exm316** [comment]
Thank you @Da0ne
