### ISSUE TITLE
Proxy export not working

### ISSUE THREAD

**Issue by robotstar78** [Da0ne/DZMods#22]
Hey. So i've tried using the proxy export function so as to add loot to my custom buildings but it comes up with the following error:

[CE][LoadPrototype] :: last group name: Rail9...
19:34:22 !!! File "mpmissions\DayZSurvival.chernarusplus\mapclusterproto.xml" does not exist...
19:34:22 !!! [CE][LoadPrototype] :: Failed to read group prototypes (mpmissions\DayZSurvival.chernarusplus\mapclusterproto.xml)
19:34:23 [CE][LoadMap] :: loaded 11553 groups, largest group range: 34.2
19:34:23 [CE][LoadClusters] :: Loading files...
19:34:23 [CE][LoadClusters] :: file: "mapgroupcluster.xml", 7 types, 50000 instances
19:34:23 [CE][LoadClusters] :: file: "mapgroupcluster01", 7 types, 50000 instances
19:34:24 [CE][LoadClusters] :: file: "mapgroupcluster02", 7 types, 50000 instances
19:34:24 [CE][LoadClusters] :: file: "mapgroupcluster03", 7 types, 44865 instances

And it is correct. There is no mapclusterproto.xml in the folder. Please help!

**Comment by robotstar78** [comment]
There is a mapgroupproto.xml, so maybe it's doing some of it, just not all?

**Comment by robotstar78** [comment]
In fact I've just noticed that now I have a billion Hele crash sites in NEAF! What the hell?! :(

**Comment by S4MT3K** [comment]
I had the same Problem... Also that Military loot was spawn in Civilian Areas. I just kept the mapgroupproto Original and only added the mapgrouppos, works Smooth :D

**Comment by robotstar78** [comment]
Ah ace dude. Thanks. I'll try it now!

**Comment by exm316** [comment]
Can I ask in which file you are inserting the code within the void???

**Comment by exm316** [comment]
Can I ask in which file you are inserting the code within the void???

**Comment by S4MT3K** [comment]
> 
> 
> Make sure you have all the xmls added into the mission. And in ModSertings.c disable debug mode

If i add all the generated files into the directory it makes the loot mixed. I have civilian loot in military areas and military loot in barns houses etc.

**Comment by robotstar78** [comment]
Mines the same. My world is a right mess now with loot spawns! I’ve got a hundred crashed helecopters at neaf and no loot, and M4s spawning in houses. Help!
    	
    	

    	Get Outlook for iOS
    
  




On Fri, Nov 2, 2018 at 9:44 PM +0000, "S4MT3K" <notifications@github.com> wrote:













Make sure you have all the xmls added into the mission. And in ModSertings.c disable debug mode



If i add all the generated files into the directory it makes the loot mixed. I have civilian loot in military areas and military loot in barns houses etc.

**Comment by S4MT3K** [comment]
Like i said: Delete the data in storage Export the xml files once. Get you a original mapgroupproto and keep it copy the generated mapgrouppos into your missions folder... And youre fine... for now.

**Comment by robotstar78** [comment]
I've done everything you said to the letter. Still no custom building loot and a thousand hele crash sites on NEAF :(

**Comment by exm316** [comment]
I am the same, well kinda.

I have done everything to the letter and when I use both the generated mapgroupproto and mapgrouppos I have no loot in the new buildings and Civ loot in Military.

When I use just the generated mapgrouppos only - I still get no loot in the new buildings but the loot in Military Areas is back to normal. 

When I look in the generated mapgrouppos the buildings I have spawned in are not in at the locations I have them?

**Comment by S4MT3K** [comment]
Honestly i cut the snippet out and implemented it it in my own Code.
But the Code is the Same. It has to be in the OnInit() function. The BuildingsSpawn procedure has to be in there aswell. When youre a good in coding, you can cut these code out and place it in the init.c just for testing. I figured out a problem with the hive thing. In some code constellations i had to place the if ce hive thing in the init to generate loot.
But when the hive stays un the init you glitch trough your new buildings. So try to generate loot in the init.c without the hive in there, if not working with hive, if still broken let me know.

Ps: i hope you guys wiped the server before you startet the lootgenerating and wipe it after again to spawn rhe new loot!

**Comment by exm316** [comment]
@S4MT3K I wiped the data folder before and after but still no joy!

**Comment by S4MT3K** [comment]
You Copied both files? Or just the mapgrouppos? Try to play around with this. Did you disabled the Debugmode and the proxyexport too? Tryied to Put the HIVE in the init and then export? If nothing will work, copy me your CustomBuildings.c Ill generate you the code!

**Comment by S4MT3K** [comment]
> Hey. So i've tried using the proxy export function so as to add loot to my custom buildings but it comes >up with the following error:
> 
> [CE][LoadPrototype] :: last group name: Rail9...
> 19:34:22 !!! File "mpmissions\DayZSurvival.chernarusplus\mapclusterproto.xml" does not exist...

> 
> And it is correct. There is no mapclusterproto.xml in the folder. Please help!

There is no such file at all. Maybe the Devs will put one in the folder. But when you install a new fresh Vanilla Server youll see there is no file named Mapclusterproto!

**Comment by exm316** [comment]
OK, I have it working.

@Da0ne the code needs changing in DayZSurvival.c

> if (m_ProxyExportMode)
> 		{
> 			CETesting TestHive = GetTesting();
> 			TestHive.ExportProxyProto();
> 			TestHive.ExportProxyData( "7500 0 7500", 15000 );
> 		}

Needs moving from line 175 to after the building spawner on line 194

Once you do that all you have to do is in _ModSettings.c_ change - _m_ProxyExportMode_ to true, Clear your data folder in _storage1_, restart your server, wait for your data folder to fully repopulise, stop your server, copy over the _mapgrouppos_ **ONLY** from the newly created export folder in _Storage1_ and change _m_ProxyExportMode_ back to flase in Modsettings.c

Restart your folder and all is good!

**Comment by exm316** [comment]
If you have problems with admin messages afterward - after you have done the above just revert the code in _DayZSurvival.c_ back to the original code!

**Comment by S4MT3K** [comment]
@robotstar78 

i cant compile your code. Youre using a other way to spawn buildings than me.
youre using entity Ai i am using Object method.

you will encounter other problems with this way. just glitch through objects missing doors etc.
or just by starting the server the yaw wont take affect on some buildings... 

try to replace it like this: then it should work with the loot generate aswell:

void BuildingSpawner() 
{
	**Object obj;**
		
		
	
**obj = GetGame().CreateObject("Land_Mil_Barracks1", "11881.500000 141.949997 12513.900391");
obj.SetOrientation("-66.200005 0.000000 0.000000");
obj.SetPosition("11881.500000 141.949997 12513.900391");**
.
.
.
etc.

ref TStringArray ZombieClasses = {
		
		the zombieclass ;D i dont copy it now 💃 
};

try it that way...
