### ISSUE TITLE
Admin tools not working

### ISSUE THREAD

**Issue by Fester808** [Da0ne/DZMods#23]
I am having an issue whereby the chat function admin tools are not working when other players are logged into the sever.

It works when I am alone on the servers or the first person to connect to the sever.

**Comment by Da0ne** [comment]
Are you using the tools only? Or the whole Vanilla++ mission? And what exactly do you mean by not working? Do you get errors? Does the chat box not give feedback after using a command? You are the only person with this issue so far. FYI: only 1 admin at a time can use the tool, and he has to be logged in first.

**Comment by Arstan13** [comment]
I am also having this issue. I see no errors through bec log or server log. just shows survivor speaking.

**Comment by Canibus** [comment]
me too, same problem. Is any solution?

**Comment by Fester808** [comment]
I am using the whole Vanilla++ mission. As Arstan said - I am not recieving any errors, crash logs etc, just as if survivor is speaking with no response from the server. For example, I type /heal and then no response. When typically it would respond with “Survivor has been healed!” or something to that afffect. 

It appears that I have fixed the issue by reinstalling the ModdedScripts folder in root directory with the files from the .zip file again (same files just reinstall). Not sure if perhaps something in that folder is writable and can get corrupt sumhow?  

I will keep you updated. Keep up the good work DaOne! You DaMan 😀👍

**Comment by AndyLee1024** [comment]
same here. i typed command "#login password", it don't show me login as admin message.

**Comment by S4MT3K** [comment]
All Messages enabled in game?

Settings—>game, lower section.
