### ISSUE TITLE
Spreading of ZedHordes spawn

### ISSUE THREAD

**Issue by S4MT3K** [Da0ne/DZMods#25]
Hy, i dont know how to communicate with you so i openend a Issue. I hope it is ok. I saw that the Spawn of the Hordes is managed by an array. Can you spread the spawn of this a bit? Maybe add a protected empty line or row or something? Or that you can Handle it like the normal zombiespawn with an radius? I would love to spread them on the runway of NWAirfield in a 300 metre radius (500-1000 zeds, i tested it, the server runs good) 💃 

Greetz S4MT3K

**Comment by Da0ne** [comment]
The array position is just used as a “centre” point. To manipulate the radius check posX and posY randomiser. Not sure what like it was, but it’s in InfecetedHordes.c in the spawn function. I will make it easy to edit in the next update :)

**Comment by S4MT3K** [comment]
Okay cool. I played a bit around with these Numbers. it is only moving the "array" around the "centre point" The zombies still stand tight together... Ill look for it next week. Now im writing classes for placeable Objects! 💯 ;)
