### ISSUE TITLE
Server is Running - Stuck at Logging in

### ISSUE THREAD

**Issue by cdb8457** [Da0ne/DZMods#28]
I followed the install %100, but when I actually try to get in the server its stuck at the log in screen.  Tried it on my test server and my PVP server.

**Comment by robotstar78** [comment]
Open up your console so you can see where it’s crashing.

**Comment by cdb8457** [comment]
I watched it this morning and no errors. This supposed to be EXP correct? All is said was that I was joining with a modified file and said I connected, but on my screen its stuck at loading.

**Comment by cdb8457** [comment]
![mpmissions](https://user-images.githubusercontent.com/21016001/48029711-81518900-e114-11e8-91fc-57f9d6e36980.PNG)

**Comment by cdb8457** [comment]
SO, this may be wrong, Do I need to put my XLMx back in?

**Comment by robotstar78** [comment]
Ok, so on first glance I can see you have no DB folder, or any of the files that would normally sit on the root of that folder. They all need to be back in there, otherwise there’s no loot table, zombie spawns, or anything.

**Comment by robotstar78** [comment]
So you definitely haven’t followed the instructions “100%” as you suggested

**Comment by cdb8457** [comment]
I am not talking bad about the project. I am trying to use this tool that a few friends have raved about. Please don't put me down about about a comment I made. I haven't ran a mod like this and I was looking for help. The direction were not made for a beginner like myself.

**Comment by cdb8457** [comment]
Delete this. I deleted myself form the DB and my character is now spawning.
