### ISSUE TITLE
Can't start mission: Can't compile "World" script module!

### ISSUE THREAD

**Issue by MrEmuu** [Da0ne/DZMods#29]
Little bit of background: 
Yes my config was setup 
No I didn't change anything in the pbo 

error: 
![image](https://user-images.githubusercontent.com/26233083/48102843-c8598000-e1e1-11e8-8d42-ec6d4464ae08.png)

Unable to compile the mission file due to these overrides but they're needed, is this due to the recent update or is this on my end? Thanks in advance.

**Comment by Da0ne** [comment]
There was a recent update to the branch, alot of things are going to be reworked, bare with me i will update the mission soon ( later today ).

**Comment by MrEmuu** [comment]
No worries! Thank you! :)

**Comment by SirFrostingham** [comment]
+1 on thanks for work, and +1 on this issue is happening for me too.
