### ISSUE TITLE
Commands Not working

### ISSUE THREAD

**Issue by HazzaOnYT** [Da0ne/DZMods#32]
Hi, 

It seems the commands are not working,
I type #login "password" on my server I can then use the bohemia commands e.g shutdown however when I put /daytime for example nothing happens am I doing it wrong ?

**Comment by HazzaOnYT** [comment]
ok

**Comment by Da0ne** [comment]
update was made to 'AdminTool.c' check the README please.

**Comment by arniegames4u** [comment]
So in my case, I'm able to login on a fresh install in do all of the commands...no problems...once I logout or the server restarts...I'm unable to use any commands despite being logged in as admin..  Any ideas?

**Comment by S4MT3K** [comment]
> 
> 
> So in my case, I'm able to login on a fresh install in do all of the commands...no problems...once I logout or the server restarts...I'm unable to use any commands despite being logged in as admin.. Any ideas?

Do you see your ServerConsole? Did it really says that you logged in? So when i log in it says: S4MT3K logged in. Check if the console tells you this  (little white window from Server) (or when you have a hoster --> DaRt)
You can also check if the ingame Messegage says_ Logged in as Admin. 
If not it isn registrating you. maybe of DB problems maybe. Do you tried the #logout command? Perhaps you have to logout first before you can login again. I can only registrate one Admin. I have a adminlist but only one can be logged in. Maybe youre still logged in but the timestamp is wrong or something. 

Hope This helps. 

Have a good day Sir :-P

Greetz S4MT3K

**Comment by arniegames4u** [comment]
Grrr. Yeah I am logged in and can see myself log out...


This message was sent from a mobile device

**Comment by arniegames4u** [comment]
I’m going to attempt a fresh install tomorrow. Will let you know what I find!


This message was sent from a mobile device
