### ISSUE TITLE
FileHandle WRITE

### ISSUE THREAD

**Issue by CurvesFR** [Da0ne/DZMods#34]
Hi, does the lastest dayz  patch resolve the FileHandle WRITE issue ? ModdedScripts.pbo doesn't write any log for now

**Comment by Da0ne** [comment]
No unfortunately hasn’t been fixed, waiting for devs to do it

**Comment by CurvesFR** [comment]
Thank you, I hope they will not decide to delete the "WRITE" method ...
In any case, congratulations for your work !
