### ISSUE TITLE
BUG REPORT #1 BY S4MT3K

### ISSUE THREAD

**Issue by S4MT3K** [Da0ne/DZMods#35]
First at all a big Thank you. Your Solution is just incredible. Never mind this way, i was literally lost and so hard confused :S but you managed it really good. Well Done Sir :D 

I played a bit around with all the Stuff and things and discovered 2 Bugs. First bug, all the food i spawn (yes im running your mod on full installation ;) ) is empty. And the second is, that some wrecks i placed in the buildingspawner.c just crash the server exe. BUGREPORT: Thread Tryied to write or read  without needed permission. Just sayin... its not that big problem. Some of your Documentation is wrong but, i saw that you will take care so i add that in LoadOuts\randomlygenerated\Readme is still ModSettings.c declared. ;) 

Ähm yes... i think this was all. 

I tried to rewrite your code for my uses but i failed... And this very hard tbh. I have 2 suggestions and a question at last: 

1.Suggestion: Managing weather. Enable/disable rain etc.
2.Spawning Multiple Items like 2 m4´s.

1. Question: I just want to spawn with static Loadout. Its a 12 case switch. Can i easyly erase your loadoutmechanic or do i have to interlace it in your randomizing? Is it still possible to ONLY spawn as "Hunter" "medic" etc? I would love if you can answer me this, when you have time. I dont want to bother your awesome work.

Greetz S4MT3K

**Comment by Da0ne** [comment]
Thanks dude! Great feedback. All the bugs mentioned have been fixed within my internal test version that I will post within the next few weeks on steam workshop when devs fix it.

**Comment by S4MT3K** [comment]
Okay, nice to hear. Im sitting here since yesterday :D I figured out that the proxy export is broken. I had an old Backupfile and all my Hangars are gone within the new method. Maybe because of that the buildings arent spawn BEFORE the export is executed? I see that some shoes are spawning when i replace it wit the new one. so anything is really bad. I can give you the files if you need them. 

Regards S4M

**Comment by S4MT3K** [comment]
OTHER SUGGESTION: 
THE HEAL COMMAND CAN BE EXTENDED WITH HUNGER AND THIRST INCREASEMENT!

`case "/heal":
								 Msgparam = new Param1<string>( "Player Healed!" );
								 GetGame().RPCSingleParam(Admin, ERPCs.RPC_USER_ACTION_MESSAGE, Msgparam, true, AdminIdentity);
								 Admin.SetHealth( Admin.GetMaxHealth( "", "" ) );
								 Admin.SetHealth( "","Blood", Admin.GetMaxHealth( "", "Blood" ) );
								 **Admin.GetStatEnergy().Add(250);
								 Admin.GetStatWater().Add(250);**
							break;`

**Comment by S4MT3K** [comment]
OTHER SUGGESTION:
THE HEAL COMMAND CAN BE EXTENDED WITH HUNGER AND THIRST INCREASMENT:

case "/heal":
								 Msgparam = new Param1<string>( "Player Healed!" );
								 GetGame().RPCSingleParam(Admin, ERPCs.RPC_USER_ACTION_MESSAGE, Msgparam, true, AdminIdentity);
								 Admin.SetHealth( Admin.GetMaxHealth( "", "" ) );
								 Admin.SetHealth( "","Blood", Admin.GetMaxHealth( "", "Blood" ) );
								 **Admin.GetStatEnergy().Add(250);
								 Admin.GetStatWater().Add(250);**
							break;

**Comment by S4MT3K** [comment]
UPDATE OF THE LOOTSPAWN ISSUE: 
You said you´ll fix this in your next Update but i post it anyway.  :-P
I wrote a admin command for the proxyexport spawned on my Server and executed the proxyexport command via admintool. It exported me 2 Files but i **ONLY** added the mapgrouppos.xml and kept the mapgroupproto.xml original.
--> everything works **EXELLENT**. When i use both the loot is mixed. (No Military loot in military areas)
Greetz S4M
