### ISSUE TITLE
Issues + Crash

### ISSUE THREAD

**Issue by Niikk0o** [Da0ne/DZMods#37]

**Comment by SirFrostingham** [comment]
A collection of all unique crash.log errors...



------------------------------------
STARSCREAM, 10.11 2018 19:40:57
NULL pointer to instance
Class:      'ZmbF_SkaterYoung_Base'
Entity id:2951859

Function: 'AfterDeath'
Stack trace:
ModdedScripts/scripts/4_World/entities\creatures\infected\zombiebase.c:88
ModdedScripts/scripts/4_World/entities\creatures\infected\zombiebase.c:35
scripts/4_World/entities\creatures\infected\zombiebase.c:99

Runtime mode
CLI params: server  mod ModdedScripts config instance\serverdz.cfg profiles instance name instance BEpath C:\Progra~2\Steam\SteamApps\common\DayZServer_P69\BattlEye cpuCount 8 exThreads 7 maxMem 20000 noPause  noSound  noLogs  adminlog  freezecheck  


------------------------------------
STARSCREAM, 10.11 2018 19:19:19
NULL pointer to instance
Class:      'SafeZone'
Function: 'SafeZoneHandle'
Stack trace:
$CurrentDir://mpmissions//DayZSurvival.chernarusplus//ScriptedMods//Modules//SafeZone//SafeZoneFunctions.c:27
$CurrentDir://mpmissions//DayZSurvival.chernarusplus//ScriptedMods//Modules//ServerMission//DayZSurvival.c:156
scripts/5_Mission/mission\missionserver.c:72
scripts/3_Game/dayzgame.c:1637

Runtime mode
CLI params: server  mod ModdedScripts config instance\serverdz.cfg profiles instance name instance BEpath C:\Progra~2\Steam\SteamApps\common\DayZServer_P69\BattlEye cpuCount 8 exThreads 7 maxMem 20000 noPause  noSound  noLogs  adminlog  freezecheck  
---------------------------------------------
Log C:\Program Files (x86)\Steam\steamapps\common\DayZServer_P69\instance\crash.log started at 10.11. 19:39:50


------------------------------------
STARSCREAM, 10.11 2018 18:38:05
NULL pointer to instance
Class:      'SurvivorBase'
Entity id:2995983

Function: 'EEKilled'
Stack trace:
ModdedScripts/scripts/4_World/entities\manbase\playerbase.c:86

Runtime mode
CLI params: server  mod ModdedScripts config instance\serverdz.cfg profiles instance name instance BEpath C:\Progra~2\Steam\SteamApps\common\DayZServer_P69\BattlEye cpuCount 8 exThreads 7 maxMem 20000 noPause  noSound  noLogs  adminlog  freezecheck  
---------------------------------------------
Log C:\Program Files (x86)\Steam\steamapps\common\DayZServer_P69\instance\crash.log started at 10.11. 18:58:03


------------------------------------
STARSCREAM, 10.11 2018 18:37:58
Calling nonexistent function on class 'M4A1'
Class:      'SurvivorBase'
Entity id:3003598

Function: 'EEKilled'
Stack trace:
ModdedScripts/scripts/4_World/entities\manbase\playerbase.c:70

Runtime mode
CLI params: server  mod ModdedScripts config instance\serverdz.cfg profiles instance name instance BEpath C:\Progra~2\Steam\SteamApps\common\DayZServer_P69\BattlEye cpuCount 8 exThreads 7 maxMem 20000 noPause  noSound  noLogs  adminlog  freezecheck  



------------------------------------
STARSCREAM, 10.11 2018 18:23:26
Calling nonexistent function on class 'AKM'
Class:      'SurvivorBase'
Entity id:2953417

Function: 'EEKilled'
Stack trace:
ModdedScripts/scripts/4_World/entities\manbase\playerbase.c:70

Runtime mode
CLI params: server  mod ModdedScripts config instance\serverdz.cfg profiles instance name instance BEpath C:\Progra~2\Steam\SteamApps\common\DayZServer_P69\BattlEye cpuCount 8 exThreads 7 maxMem 20000 noPause  noSound  noLogs  adminlog  freezecheck  


------------------------------------
STARSCREAM, 10.11 2018 18:25:07
Calling nonexistent function on class 'Mp133Shotgun'
Class:      'SurvivorBase'
Entity id:2999437

Function: 'EEKilled'
Stack trace:
ModdedScripts/scripts/4_World/entities\manbase\playerbase.c:70

Runtime mode
CLI params: server  mod ModdedScripts config instance\serverdz.cfg profiles instance name instance BEpath C:\Progra~2\Steam\SteamApps\common\DayZServer_P69\BattlEye cpuCount 8 exThreads 7 maxMem 20000 noPause  noSound  noLogs  adminlog  freezecheck  


------------------------------------
STARSCREAM, 10.11 2018 18:14:58

[cheat] man=SurvivorBase<d66432e0> is cheating with cmd=SYNC_MOVE src={ type=GROUND item=Tomato<662f4320> pos=(14149.7, 3.84583, 12998.3) dir=(0, 0, 0, 1) } dst={ type=CARGO item=Tomato<662f4320> parent=Clothing<583c3d80> idx=0 row=0 col=1 }
Class:      'DayZPlayerInventory'
Function: 'Error'
Stack trace:
scripts/1_Core/proto\endebug.c:44
scripts/4_World/systems\inventory\dayzplayerinventory.c:331
scripts/4_World/systems\inventory\dayzplayerinventory.c:283

Runtime mode
CLI params: server  mod ModdedScripts config instance\serverdz.cfg profiles instance name instance BEpath C:\Progra~2\Steam\SteamApps\common\DayZServer_P69\BattlEye cpuCount 8 exThreads 7 maxMem 20000 noPause  noSound  noLogs  adminlog  freezecheck  


------------------------------------
STARSCREAM, 10.11 2018 18:15:58
Calling nonexistent function on class 'ZmbF_MilkMaidOld_Base'
Class:      'SurvivorBase'
Entity id:2999457

Function: 'EEKilled'
Stack trace:
ModdedScripts/scripts/4_World/entities\manbase\playerbase.c:70

Runtime mode
CLI params: server  mod ModdedScripts config instance\serverdz.cfg profiles instance name instance BEpath C:\Progra~2\Steam\SteamApps\common\DayZServer_P69\BattlEye cpuCount 8 exThreads 7 maxMem 20000 noPause  noSound  noLogs  adminlog  freezecheck  


------------------------------------
STARSCREAM, 10.11 2018 18:14:16
NULL pointer to instance
Class:      'SafeZone'
Function: 'SafeZoneHandle'
Stack trace:
$CurrentDir://mpmissions//DayZSurvival.chernarusplus//ScriptedMods//Modules//SafeZone//SafeZoneFunctions.c:27
$CurrentDir://mpmissions//DayZSurvival.chernarusplus//ScriptedMods//Modules//ServerMission//DayZSurvival.c:156
scripts/5_Mission/mission\missionserver.c:72
scripts/3_Game/dayzgame.c:1637

Runtime mode
CLI params: server  mod ModdedScripts config instance\serverdz.cfg profiles instance name instance BEpath C:\Progra~2\Steam\SteamApps\common\DayZServer_P69\BattlEye cpuCount 8 exThreads 7 maxMem 20000 noPause  noSound  noLogs  adminlog  freezecheck

**Comment by cdb8457** [comment]
NULL pointer to instance
Class:      'AdvancedLoadouts'
Function: 'SpawnGunIn'
Stack trace:
$CurrentDir://mpmissions//DayZSurvival.chernarusplus//ScriptedMods//Modules//AdvancedLoadouts//AdvancedLoadouts.c:596
$CurrentDir://mpmissions//DayZSurvival.chernarusplus//ScriptedMods//Modules//ServerMission//DayZSurvival.c:240
scripts/5_Mission/mission/missionServer.c:316
scripts/5_Mission/mission/missionServer.c:351
scripts/5_Mission/mission/missionServer.c:149
$CurrentDir://mpmissions//DayZSurvival.chernarusplus//ScriptedMods//Modules//ServerMission//DayZSurvival.c:174
scripts/3_Game/DayZGame.c:867
