### ISSUE TITLE
Add new mods

### ISSUE THREAD

**Issue by evansalles** [Da0ne/DZMods#38]
Hello, if you can help it will be great.
I can't make the mod of AirDrop.c to run with this mod.
In tutorial on how to install it says to find "class CustomMission : MissionServer" and put the code inside class, I was able to find it inside "DayZSurvival.c" but it does not work.
Any ideas how to make it work?
Thanks for you time.

**Comment by TermNCR** [comment]
lol here;
change to 
```css
class DayZSurvival : MissionServer
```

I run this, you need to rewrite the script as since BETA this script will not work.

**Comment by TermNCR** [comment]
mark as closed.

**Comment by evansalles** [comment]
Hello,
There is already a "_class DayZSurvival: MissionServer_" inside "_DayZSurvival.c_"
What I did was write the AirDrop code inside it, but it does't work.
`ref AirDrop AirDropClass; // Class definition

void CustomMission()
{
	AirDropClass = new AirDrop;		
}

float TimerSlice; // Timeslice
override void OnUpdate( float timeslice )
{
	super.OnUpdate( timeslice );

	// FPS Fix
	TimerSlice += timeslice;
	if (TimerSlice >= AirDropClass.TimesliceMultiplyier)
	{
		AirDropClass.CreateAirDrop();
		TimerSlice = 0;	
	}
}`

I'm not a programer so I can't undertand the code very well, but I'm intent. I've been struggling to make this work for days. Really nice if you could help me.

**Comment by evansalles** [comment]
Did you rewrite it? Can you send me your AirDrop.c file?
There is a topic at AirDrop github page about it, but no response yet. Waiting to mov3ax to have a free time and help us all

**Comment by TermNCR** [comment]
Ive contacted mov3ax and will not update it, he wants on the steamworkshop as a mod now. Check there to see if its been uploaded.

Nah im not sharing someones else code that I have janked up to get working sorry. 

getting offtopic here so mark as closed 👍

**Comment by evansalles** [comment]
Ok no problems, thanks for your time.
