### ISSUE TITLE
Map Loads, Game is Joinable, but not players or items are loaded.

### ISSUE THREAD

**Issue by cdb8457** [Da0ne/DZMods#39]
I can join the game and the map loads, but console seems it not loading storage or mission. 
![start](https://user-images.githubusercontent.com/21016001/48303395-58901180-e4cf-11e8-9ffd-eb3ee5a6ae2f.PNG)

![daone](https://user-images.githubusercontent.com/21016001/48303399-6b0a4b00-e4cf-11e8-8e65-8a32e6adfccf.PNG)

**Comment by CurvesFR** [comment]
In Tunables.c, try to set m_Debugmode to false

**Comment by cdb8457** [comment]
![attachedhandle](https://user-images.githubusercontent.com/21016001/48306407-bb989d00-e4fd-11e8-93ca-5ad993edb765.PNG)

I have had this problem before and fixed it, but I cannot fix it.

**Comment by arniegames4u** [comment]
I'm having the same issue...I turned off the zombie horde in tunables.c and
the server works without them.

**Comment by cdb8457** [comment]
I set it to false and still have the same error
