### ISSUE TITLE
Safezone/Godmode

### ISSUE THREAD

**Issue by S4MT3K** [Da0ne/DZMods#4]
Hey, i figured out that the Safezone isnt a Safezone at all. I understand why (Healcenter thing) but can you tell me what i have to change that the Player is 100% Bulletproof? Cause we tryied yesterday to messure the Zone and getting Shot and were killed. And thats an issue! Thanks greetz S4MT3K

**Comment by zalexki** [comment]
this is not possible at the moment

**Comment by Da0ne** [comment]
yes i should have mentioned it in the Readme, there is no 100% godmode due to the nature of the engine at the moment. All the hit reg stuff is hard codded. All we have access to is a few trigger events that happen after most important calculations. Sooner or later it will change "fingers crossed"
