### ISSUE TITLE
How to remove the inscription at the beginning "Survivor:" of messages? 

### ISSUE THREAD

**Issue by JackSmithRU** [Da0ne/DZMods#41]
![image](https://user-images.githubusercontent.com/44942334/48327461-af8e1600-e68a-11e8-98cf-9200bebbc003.png)

**Comment by S4MT3K** [comment]
Add in your Server start batch file -name=Yourname

**Comment by JackSmithRU** [comment]
@S4MT3K Thanks!

**Comment by LArtDesChOiX** [comment]
TY, i've an auto installer with VILAYER and i no see the start.bat in the root folder.. I need create one ??
I need help for create one please ! :)
