### ISSUE TITLE
Score tracking system and Kill Activity tracker

### ISSUE THREAD

**Issue by fabienthomas** [Da0ne/DZMods#42]
Hello, 
Firstly : Thanks, you've done an awesome work !

I have an issue with "score tracking system and Kill Activity tracker". 
I can't find any files exported in my computer, i've searched, a lot, but found nothing

Would you share some precisions about that feature ?

**Comment by Da0ne** [comment]
add the following param to your server: -scrAllowFileWrite

**Comment by fabienthomas** [comment]
> add the following param to your server: -scrAllowFileWrite

It works like a charm now !
Thank you sir !
