### ISSUE TITLE
Using command tpc teleports me to water

### ISSUE THREAD

**Issue by evansalles** [Da0ne/DZMods#44]
Hello,
I'm trying to use the command to spawn next to helicrashs so I can see if my changes at loot spawn is ok.
But every time I'm teleported to water, like in the middle of the sea.
I'm using coords i've found at cfgeventspawns.xml
The command i'm using is "/tpc xxxxx zzzzz aaaaa"

**Comment by evansalles** [comment]
Neverming, I'm an idiot. Was using the command wrong.
The right use is "/tpc xxxx aaaaa zzzz"

**Comment by S4MT3K** [comment]
Can you tell me how you changed the loot there? I cant find the preset :/

**Comment by evansalles** [comment]
At mapgroupproto.xml look for "Wreck_Mi8" and "Wreck_UH1Y"

**Comment by S4MT3K** [comment]
@evansalles  Thanks mate.
