### ISSUE TITLE
Welp...I need some help

### ISSUE THREAD

**Issue by cdb8457** [Da0ne/DZMods#45]
In Bec I can see the messages showing, but they do not show up in the  game. My admin tools work, but my hordes and what you spawn with are not working. My player spawn messages are not working either.Spawn with a white bandage and a silencer and clips. Any ideas. I "thought" I had things in the right spot do to the admin tool at least working and half of the spawning gear working.

**Comment by S4MT3K** [comment]
Excuse the dumb question, but did you enabled all Messages? Can find it in settings-->game...

**Comment by cdb8457** [comment]
Welp, Where can I do that at? Ha Sorry

**Comment by S4MT3K** [comment]
You go INGAME into your settings. Most like the first opened section is the right one. Down below (lower part) are the settings for messaging behavior.

**Comment by cdb8457** [comment]
Geeze.....They have been working the whole time.....
