### ISSUE TITLE
  I added a function, but there are some problems.

### ISSUE THREAD

**Issue by chinayern** [Da0ne/DZMods#46]
I added a function and an option.

Input command /spgs ItemClass quantiy

The incoming quantity is a string, how to convert it into a number?

**Comment by chinayern** [comment]
like this
`	void oSpawnItemsFunc( PlayerBase player, string ClassName ,int num)
	{
		EntityAI items;

		vector NewPosition;
		vector OldPosition;

		OldPosition = player.GetPosition();

		NewPosition[0] = OldPosition[0] + 1.5;
		NewPosition[1] = OldPosition[1] + 0.5;
		NewPosition[2] = OldPosition[2] + 1.5;
		for(int i = 0; i < num;i++)
		{
			items = GetGame().CreateObject( ClassName, NewPosition, false, true );
		}

	}`

**Comment by chinayern** [comment]
I have an idea. 
After a few hours, there was news that a town would have a large supply of materials, and there were plenty of zombies. Provide players with targeted competition and war.

**Comment by BorizzK** [comment]
Now need to use ItemBase.Cast for safe downcasting
If items is ItemBase
items = ItemBase.Cast(GetGame().CreateObject(ClassName,NewPosition, false,True));
Becouse CreateObject  creates an object of class object, not playerbase

**Comment by chinayern** [comment]
> 
> 
> Now need to use ItemBase.Cast for safe downcasting
> If items is ItemBase
> items = ItemBase.Cast(GetGame().CreateObject(ClassName,NewPosition, false,True));
> Becouse CreateObject creates an object of class object, not playerbase

I can't solve the chat input "/spgs mag_stanag_30rnd 30".

This 30 is a string, how to import oSpawnItemsFunc (Admin, "mag_stanag_30rnd", "30").

Error "30" not int


Items = GetGame ().CreateObject (ClassName, NewPosition, false, true);

it's available that

**Comment by chinayern** [comment]
Now I can use this fixed number.


case "/spgs":
								oSpawnItemsFunc(Admin,cData,10);
								strMessage = "Admin Commands: Items " + cData + " Spawned around you!";
								Msgparam = new Param1<string>( strMessage );
								GetGame().RPCSingleParam(Admin, ERPCs.RPC_USER_ACTION_MESSAGE, Msgparam, true, AdminIdentity);
							break;

**Comment by S4MT3K** [comment]
> 
> 
> Now I can use this fixed number.
> 
> case "/spgs":
> oSpawnItemsFunc(Admin,cData,10);
> strMessage = "Admin Commands: Items " + cData + " Spawned around you!";
> Msgparam = new Param1( strMessage );
> GetGame().RPCSingleParam(Admin, ERPCs.RPC_USER_ACTION_MESSAGE, Msgparam, true, AdminIdentity);
> break;

Can you post the code? I tried to manage it with your snippets but it says wrong nmber of template parameters --> Im not that far with templates =/ i still stuck on classes with learning c++
Would be very nice. 

Greetz S4MT3K

**Comment by chinayern** [comment]
S4MT3K ,You need to add this function. 
void oSpawnItemsFunc( PlayerBase player, string ClassName ,int num)
{
EntityAI items;
	vector NewPosition;
	vector OldPosition;

	OldPosition = player.GetPosition();

	NewPosition[0] = OldPosition[0] + 1.5;
	NewPosition[1] = OldPosition[1] + 0.5;
	NewPosition[2] = OldPosition[2] + 1.5;
	for(int i = 0; i < num;i++)
	{
		items = GetGame().CreateObject( ClassName, NewPosition, false, true );
	}

}

**Comment by S4MT3K** [comment]
case "/spgs":
oSpawnItemsFunc(Admin,cData,10);
strMessage = "Admin Commands: Items " + cData + " Spawned around you!";
Msgparam = new Param1**<string>**( strMessage );
GetGame().RPCSingleParam(Admin, ERPCs.RPC_USER_ACTION_MESSAGE, Msgparam, true, AdminIdentity);
break;

Above is the correct case. you forgot a string that was my Template error. Now it works... Thx

**Comment by chinayern** [comment]
Do you know how to split strings? The method in c++ cannot be used.
cData="className Number"
Conform to split str1 str2
str1="className"
str2="Number"

**Comment by chinayern** [comment]
I fix it.
But you can't use "/ spgs" which is too similar to "/ spg"
Somehow it's linked to the "/spg" function

case "some":
							TStringArray TSA = new TStringArray;
							cData.Split(" ",TSA);
							/*
							int startIndex = cData.IndexOf(" ");
							string itemName = cData.Substring(0,startIndex);
							string itemQuantity = cData;
							*/
							oSpawnItemsFunc(Admin,TSA.Get(0),TSA.Get(1).ToFloat());
							strMessage = "Admin Commands: Item " + TSA.Get(0) + "  Quantity: " + TSA.Get(1) ;
							Msgparam = new Param1<string>( strMessage );
							GetGame().RPCSingleParam(Admin, ERPCs.RPC_USER_ACTION_MESSAGE, Msgparam, true, AdminIdentity);
							
						break;

**Comment by S4MT3K** [comment]
Am i have another Server?!?!
Everything was working like a charm.

Spgs command works 100% o.O

It even works with spawncar 😂

**Comment by chinayern** [comment]
😂hahahahahahahahaha
