### ISSUE TITLE
SUGGESTION/QUESTION #1 BY S4MT3K

### ISSUE THREAD

**Issue by S4MT3K** [Da0ne/DZMods#47]
I tried a bit around but can´t find a Solution for this.

I wanted to Stop the timer of the ZombieHordes or add a restock to them when you in near of them...
It happened that we were on way to NWAF and saw the Horde. We wanted to Sneak around and suddenly they are gone. This wasnt funny =(. Is there a way to restock or stop the Timer when a Player is near the Horde? And when yes, can you post a code for that?

Can you Maybe Update your Repo to your New Update? I cant wait for it come to Steam Workshop *cry* ^^

Greetz S4MT3K

**Comment by Da0ne** [comment]
Yea thats a good point, i have not done much with the zombie hordes but functions as you mentioned are for sure going to be part of the mod. The trigger will be more extensive and it will report back activity that occurs during the event eg, someone starts killing the zombie it will trigger a specif status with a message or anything else the admin wants to make/add.

No sorry im not ready to release the new update, its a big one as im adding UI support for things. Im giving it one more week till workshop is fixed. Plus there is still more work i wanna do on the mod

**Comment by S4MT3K** [comment]
Okay No Problem :D I just cant wait ^^ Just awesome from now. And GUI is a must have... Thanks for your Work. I made a few changes in your code over the fork function here. I dont really know what this is, but if you did not saw it take a look. Just little things, but maybe helpful...
Have a nice Day :-D

Greetz S4MT3K
