### ISSUE TITLE
  I want to submit a function. “/userlist”

### ISSUE THREAD

**Issue by chinayern** [Da0ne/DZMods#52]
case "/userlist":
								for ( int usersNum = 0; usersNum < players.Count(); ++usersNum )
								{
									selectedPlayer = players.Get(usersNum);
									selectedIdentity = selectedPlayer.GetIdentity();
									strMessage = "User:" + selectedIdentity.GetName() + " POS:" + selectedPlayer.GetPosition();;
									Msgparam = new Param1<string>( strMessage );
									GetGame().RPCSingleParam(Admin, ERPCs.RPC_USER_ACTION_MESSAGE, Msgparam, true, AdminIdentity);
								}
							break;

I hope it can be included in your next version.

Best Wishes For You!

**Comment by S4MT3K** [comment]
The Function selectedPlayer.GetPosition(); Whats their return? Will it return the Whole xxxx aaaa zzzzz?

BTW: After get position in your code theres a double semicolon;)
Nice Function though. Copied and included :P 

Thx for that.

Greetz S4MT3K

**Comment by robotstar78** [comment]
Hm, doesn't seem to work for me. I get the following. Already changed the double semicolon..

ZARE5, 19.11 2018 19:44:45
Can't compile mission init script'!
 
$CurrentDir://mpmissions//DayZSurvival.chernarusplus//ScriptedMods//Modules//AdminTool//AdminTool.c(456): Wrong number of template parameters
 
Runtime mode
CLI params: config Config.cfg ip 109.230.215.98 port 2302 profiles SC name SC BEpath SC\Battleye mod ModdedScripts adminlog

**Comment by S4MT3K** [comment]
Try #46

**Comment by S4MT3K** [comment]
I figured out the issue. This github Texteditor does not allow "<" and ">" so you have to write "string" manually (Without quotation marks) and with "<" ">" without quotationmarks aswell.

case "/userlist":
for ( int usersNum = 0; usersNum < players.Count(); ++usersNum )
{
selectedPlayer = players.Get(usersNum);
selectedIdentity = selectedPlayer.GetIdentity();
strMessage = "User:" + selectedIdentity.GetName() + " POS:" + selectedPlayer.GetPosition();;
Msgparam = new Param1"<"**string**">"( strMessage );
GetGame().RPCSingleParam(Admin, ERPCs.RPC_USER_ACTION_MESSAGE, Msgparam, true, AdminIdentity);
}
break;

The same for all missed strings after the param1

**Comment by chinayern** [comment]
This is indeed the case.
