### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by Corpulio** [Da0ne/DZMods#57]
I have this problem:
Can’t compile mission init script!

$CurrentDir:mpmissions\dayzOffline.chernarusplus\init.c(33): Opened scope at the end of file, missing ‘}’ ?

**Comment by S4MT3K** [comment]
Do you made some changes in the code?

**Comment by chinayern** [comment]
Please read "readme"

**Comment by Corpulio** [comment]
Nothing changed in the code! When i delete code from init.c then the server work perfect!

Yes, i read “reademe” but dont solve my problem!

**Comment by Corpulio** [comment]
I put this code the original init.c and have a same problem!

**Comment by chinayern** [comment]
> I put this code the original init.c and have a same problem!
I don't understand you. 
Have you put the ModdedScripts directory under DayZServer? 

Is DayZServer\mpmissions\DayZSurvival.chernarusplus in the correct directory?

**Comment by Corpulio** [comment]
I use this:
https://opendayz.net/threads/chat-based-admin-tool-set.22394/

**Comment by chinayern** [comment]
Sure enough, this statement is incomplete. 

Why not read Da0ne  redme? 

How to Setup
IMPORTANT : For those who own a server provide by www.Vilayer.com, can auto install the mod via the AddonManager (special thanks goes to the Vilayer team)!

Step One:
Go to your server directory and create a folder, name the folder what ever you desire son. (just give it a damn name that is not NewFolder)
Step Two:
open the folder 'mpmissions' in your server directory, copy the file 'DayZSurvival.chernarusplus' and place it in there. (If you had any edits done to your loot xmls and wish to keep the storage make sure you replace it with the ones that are in 'DayZSurvival.chernarusplus' ) The db folder contains NO MODDED features/changes its all vanilla same goes with other xmls. Replace it with your modded xmls if you wish to.
Step Three:
The server config file 'serverDZ.cfg' is in the main directory (Vanilla Fresh copy from steam), MOVE that file into the folder you created in step 1 Open up the config file and go to the bottom where you see 'dayzOffline.chernarusplus' REPLACE IT with 'DayZSurvival.chernarusplus' Save and exit.
Step Four:
Place the foler 'ModdedScripts' into your main DayZ Server directory where the .exe is and all that stuff.
Step Five:
add the following startup command lines to your server: -mod=ModdedScripts -config=NameOfFolderFromStep1\serverDZ.cfg -profiles=NameOfFolderFromStep1 -name=myServerName The -name command will change the name that shows up in global chat. When players join/leave/getkilled and other GlobalMessages. if you wish to actiavte any other mods listed in the Features list. Just add the command line to whatever starts your server exe.

**Comment by Corpulio** [comment]
Thx! I dont need modded scripts! I need only admin tool! Nothing else. So i wait other admin tool. And i run dedi server not vilayer or other hosted server. 
But thank you for the help!
