### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by MannieJay** [Da0ne/DZMods#58]
Fresh install of server and fresh clone of DZMods. No code changes of any kind. 

Can't compile mission init script'!

$CurrentDir://mpmissions//DayZSurvival.chernarusplus//ScriptedMods//Modules//ServerEvents//InfectedHordes.c{89): Undefined function 'AttachEventHandle'

**Comment by chinayern** [comment]
Please read "readme"

**Comment by MannieJay** [comment]
Yep, I missed a step sorry about that.
