### ISSUE TITLE
Where to edit the player join/leave message and safezone messages not working

### ISSUE THREAD

**Issue by RealShu** [Da0ne/DZMods#6]
In the readme it says to look at the file "settings.c" for the player join/leave messages but there is no file named that. Also I have gotten most things to work but when I go to the safezone position I set no enter or leave message shows. I do have the safezones enabled.

**Comment by S4MT3K** [comment]
The code for the joining thing is in the ModdedScripts.pbo...

**Comment by RealShu** [comment]
> The code for the joining thing is in the ModdedScripts.pbo...
> The SafeZone must be set in the SafeZoneFunctions.c

Already set the safezone and as for the moddedscripts.pbo there is no file in there called settings.c

**Comment by RealShu** [comment]
> > > The code for the joining thing is in the ModdedScripts.pbo...
> > > The SafeZone must be set in the SafeZoneFunctions.c
> > 
> > 
> > Already set the safezone and as for the moddedscripts.pbo there is no file in there called settings.c
> 
> Im sorry my explaination was very bad... in the .pbo you have to navigate to playerbase.c. In this file you can search for player joined and see the code... My Safezone is working, so maybe you just have to check your installation?!?!?!

ok i see thankyou. also for the safezone i put the coords in from isurvive but as i said they do not work. What should i do?

**Comment by RealShu** [comment]
not seeing any connect messages either. follwed the install step and did everything.

**Comment by snigelx** [comment]
I must delete the Storage folder then Works , try it .

**Comment by RealShu** [comment]
> I must delete the Storage folder then Works , try it .

still does not work. currently the only things that work are the loadouts and admin tools

**Comment by S4MT3K** [comment]
Do you added it to an existing Server or just installed it to a fresh server? In some cases the existing init.c causes problems... I figured out that a double hive command will cause this and can disabling the heigh from buildings you placed...

**Comment by snigelx** [comment]
> 
> 
> > I must delete the Storage folder then Works , try it .
> 
> still does not work. currently the only things that work are the loadouts and admin tools

not more ?
What´s with the Suicide Message ? Player Count etc ? Nothing works ?
Try to Change the Instance folder eg. -Instance2 / Clear Storage Folder .

It works Really , try it out

**Comment by RealShu** [comment]
> Do you added it to an existing Server or just installed it to a fresh server? In some cases the existing init.c causes problems... I figured out that a double hive command will cause this and can disabling the heigh from buildings you placed...

I tried a fresh mission file and still same stuff doesnt work. guess i can try a fresh server install

**Comment by RealShu** [comment]
> > > I must delete the Storage folder then Works , try it .
> > 
> > 
> > still does not work. currently the only things that work are the loadouts and admin tools
> 
> not more ?
> What´s with the Suicide Message ? Player Count etc ? Nothing works ?
> Try to Change the Instance folder eg. -Instance2 / Clear Storage Folder .
> 
> It works Really , try it out
Death messages, player connect/disconnect and the safezone are the thigns that dont work

**Comment by RealShu** [comment]
After a fresh server install I have gotten safezones to work but the player connect and death messages still do not

**Comment by Da0ne** [comment]
> After a fresh server install I have gotten safezones to work but the player connect and death messages still do not

If you are missing 'modsettings.c' means your version is outdated. Download the the needed updated files. aka the whole mission. For future immunity from updates breaking your mods (the mods you add on top of my mission) make them external. If you don't have any code backrground knowledge, its gonna be tough... this is not user friendly yet, im trying my best with making it easy to edit and add more mods on top. A new update is due soon. Possibly Wednesday next week.

**Comment by RealShu** [comment]
> > After a fresh server install I have gotten safezones to work but the player connect and death messages still do not
> 
> If you are missing 'modsettings.c' means your version is outdated. Download the the needed updated files. aka the whole mission. For future immunity from updates breaking your mods (the mods you add on top of my mission) make them external. If you don't have any code backrground knowledge, its gonna be tough... this is not user friendly yet, im trying my best with making it easy to edit and add more mods on top. A new update is due soon. Possibly Wednesday next week.

i am not missing modsettings.c also it seem the its just death messages and player connect that dont work so i guess my server is executing the moddedscripts folder

**Comment by RealShu** [comment]
Enable/Disable player Join/leave messages. Check the file "Settings.C"

I do not have this file.
