### ISSUE TITLE
cant get loot in custom buildings

### ISSUE THREAD

**Issue by sy8282** [Da0ne/DZMods#62]
not sure what im doing wrong 
tried the oninit advice in the pastebin file but no sign of an export folder anywhere
tried the suggestion of moving the CEtesting code to the bottom of the list in dayzsurvival.c

**Comment by S4MT3K** [comment]
You have to make sure that the buildings Spawning BEFORE the ce Hive code is executed!!!!

My tip: Copy a case in the admin tool (dont forget to registrate it in the upper section) Name it: proxyexportand execute it via Adminlogin INGAME!

m_ExtendedCommands.Insert("/proxyexport", 1); //IN THE UPPER SECTION

case "/proxyexport": //BETWEEN THE EXISTING CASES!
								CETesting TestHive = GetTesting();
								TestHive.ExportProxyProto();
								TestHive.ExportProxyData("7500 0 7500", 12000);
break;

**Comment by sy8282** [comment]
im now having issue with admin tool its not responding to any commands was working fine on friday

**Comment by sy8282** [comment]
my bad,
I got it cheers buddy 
worked like a charm

**Comment by S4MT3K** [comment]
@Da0ne Can you confirm it too that this problem is occurring? I mean i dont want to change your code, thats rude, but with your way of proxyexport, it isnt working =(

**Comment by sy8282** [comment]
the proxyexport worked but since then i got no military loot in mili bases only civilian loot any fix?

**Comment by wydox1SK** [comment]
> the proxyexport worked but since then i got no military loot in mili bases only civilian loot any fix?

I had the same issue when i tried to put custom buildings in, must be fucked.

**Comment by S4MT3K** [comment]
When you exported the Files, only use the mapgrouppos.xml
The mapgroupproto.xml stays original.

**Comment by wydox1SK** [comment]
> When you exported the Files, only use the mapgrouppos.xml
> The mapgroupproto.xml stays original.

Does that have anything to do with the fact that it changes the normal spawns of military gear?
Or the issue that custom military buildings do not spawn military gear?

**Comment by S4MT3K** [comment]
It is because the new file has no usage tags. You had to manually add them. I compared both files. You can really take the original one. I think somethinh is broken (or purposed to be) that the loot is „main“ at first, and then added military areas manually. I think thats how the vanilla mapgroupproto occur!

**Comment by sy8282** [comment]
I thought I was going mad, had players moaning there wax no military loot, and me telling them just because you don't see another player doesn't mean they aren't there etc

**Comment by S4MT3K** [comment]
Unfortunately True :(

Is your LootProblem fixed?

**Comment by wydox1SK** [comment]
> It is because the new file has no usage tags. You had to manually add them. I compared both files. You can really take the original one. I think somethinh is broken (or purposed to be) that the loot is „main“ at first, and then added military areas manually. I think thats how the vanilla mapgroupproto occur!

Hey just wondering what you mean by adding the tags manually?

I can see the issue that the new mapgroupproto does not have tags added, are you saying i need to edit the new exported mapgroupproto and add all the tags for every loot spawn? That doesn't seem very realistic. Is there a way i can add my new military building to the already existing vanilla mapgroupproto?

**Comment by sy8282** [comment]
Wydox1sk, He is saying only use the mapgrouppos and it will be fine.

S4MT3K, just as you told me the fix my id's woke up so not had a chance to test yet I'll report back when I get a chance to fix it

**Comment by S4MT3K** [comment]
@wydox1SK
I mean that you had to, if you not already had the existing mapgrouptot.xml. You Only have to replace the existing mapgrouppos.xml with the original one. Keep the mapgroupprot.xml untouched. Both of them!

@sy8282 
Ok, i wait for your report :)

**Comment by wydox1SK** [comment]
@S4MT3K 

Ive tested it and everything works fine, thank you very much for the help!

**Comment by S4MT3K** [comment]
Im just standing around and keep things together... The real amazing work is done by DaOne... Hes the legend ;) But thanks :-*
