### ISSUE TITLE
 'AttachEventHandle' error after update

### ISSUE THREAD

**Issue by RealShu** [Da0ne/DZMods#67]
My server was currently running everything fine. Updated the server to the latest patch and now getting this error on startup - $CurrentDir://mpmissions//dayzsurvival.chernarusplus//ScriptedMods//Modules//ServerEvents//InfectedHordes.c(89): Undefined function 'AttachEventHandle'

**Comment by modernkilla82** [comment]
if mod is 100% running it shouldnt give that message-
