### ISSUE TITLE
Godmode (only Info)

### ISSUE THREAD

**Issue by Sniy** [Da0ne/DZMods#7]
I know Dayz isnt finish . But the Godmode doesnt run 100 % . Zombies give me no Damage but Wolves killed me . (seems like is a missed feature or anything)

Good Job Da0ne.
Only a Info . Thx

**Comment by Sniy** [comment]
Okay , many thx :)

**Comment by Sniy** [comment]
Oh, dying is part of DayZ, right? : D

**Comment by S4MT3K** [comment]
Yes, but not if you are in Development state and dont want to :D I mean: SafeZone is just a word, it becomes what you want to be. It would be nice to disable the Damage of guns or just make them unavailable. I searched the code for that but only found a way to disable hunger and thirst. For now it is ok but in the future it would be nice to disable firearms. Fists and melee weaphons is ok to use in there just for fun (that the flair of dayZ wont go, keep an eye on everybody... dont trust anybody ) :D

**Comment by Sniy** [comment]
Yes you are right .
I'm not the best "coder", I'm desperately trying to get the tents started today. No chance. I also do not want a solution for getting it myself makes it more fun right?
What a pity I find "OffTopic" is the development of the game itself. So much time, so much money and and and .... many of my friends are playing and do not want to play anymore.
