### ISSUE TITLE
Mod Crashes Server When Players Spawn in, with Static Classes

### ISSUE THREAD

**Issue by W-Schlesner** [Da0ne/DZMods#75]
![2310df6ddbe73508826a416cc39678a1](https://user-images.githubusercontent.com/11034865/48996249-67a2d080-f119-11e8-809e-b4bd804a4fae.png)

This is my Crash Log once the server Crashes. I've looked into it and I can't find a fix for it.

**Comment by GravityWolfNotAmused** [comment]
This doesn't seem like a mod issue since the stacktrace starts in a native DayZ file. Are you still having issues?

**Comment by W-Schlesner** [comment]
I fixed the problem. I was something to do with my Custom Classes. Thank you

**Comment by GravityWolfNotAmused** [comment]
Do you have -srcAllowFileWrite inside of your start up parameters?
