### ISSUE TITLE
Add Two function

### ISSUE THREAD

**Issue by chinayern** [Da0ne/DZMods#77]
Comments or suggestions are welcome.
`
case "/tptp":
							TStringArray tpName = new TStringArray;
							cData.Split(" ",tpName);
							bool locaBreak = true;
							bool tpBreak = true;
							PlayerBase locaPlayer,tpPlayer;
							if(tpName.Count() != 2)
							{
								break;
							}

							for ( int x = 0; x < players.Count(); ++x )
							{
								if(players.Get(x).GetIdentity().GetName() == tpName.Get(1) )
								{
									locaPlayer = players.Get(x);
									locaBreak = false;
								}
								if(players.Get(x).GetIdentity().GetName() == tpName.Get(0) )
								{
									tpPlayer = players.Get(x);
									tpBreak = false;
								}
							}

							if(locaBreak == true || tpBreak ==true)
							{
								break;
							}else{
								tpPlayer.SetPosition(locaPlayer.GetPosition());
								strMessage = "Player " + tpName.Get(0) + " was teleported to " + tpName.Get(1) + " location!";
								Msgparam = new Param1<string>( strMessage );
								GetGame().RPCSingleParam(Admin, ERPCs.RPC_USER_ACTION_MESSAGE, Msgparam, true, AdminIdentity);
							}
						break;

						case "/tptc":
							int start = cData.IndexOf(" ");
							PlayerBase tpcPlayer;
							string tpcName;
							tpcName = cData.Substring(0,start);
							cData.Replace(tpcName + " ","");
							vector tpcPos = cData.ToVector();
							vector fixtpcPos;
							fixtpcPos[0] = tpcPos[0];
							fixtpcPos[2] = tpcPos[2];

							fixtpcPos = SnapToGround( fixtpcPos );
							for ( int y = 0; y < players.Count(); ++y )
							{
								if(players.Get(y).GetIdentity().GetName() == tpcName)
								{
									tpcPlayer = players.Get(y);
								}
								else{
									break;
								}
							}
							tpcPlayer.SetPosition(fixtpcPos);

							strMessage = tpcName + "Teleported to:: " + tpcPos;
							Msgparam = new Param1<string>( strMessage );
							GetGame().RPCSingleParam(Admin, ERPCs.RPC_USER_ACTION_MESSAGE, Msgparam, true, AdminIdentity);
						break;
`

**Comment by S4MT3K** [comment]
Teleport Player A to Player B 
and
Teleport Player A to Coordinates.
If anybody wonders :P

**Comment by S4MT3K** [comment]
Can you tell me how the usage is of this things? I Only compiled it but not tested it. The tptc command semms to not work. Thanks :D

**Comment by chinayern** [comment]
Run like this：
/tptp  chinayern S4MT3K
cmd name name
/tptc S4MT3K 2400 0 2400
cmd name x z y

**Comment by S4MT3K** [comment]
Okay, it wont teleport the player to the Coordinates. It says: Player Chinayern teleported to 2400 0 2400 but you stand still where you bin. No teleportation.
I read the code, cant find a error.

**Comment by chinayern** [comment]
The code working in my server.
Names are case-sensitive and must not be misspelled.

If the name is Survival (?)

May not be able to TP

**Comment by chinayern** [comment]
You can use /tptc to Teleport yourself and test whether this function works.
Then try to transfer other players with a custom name.
