### ISSUE TITLE
LootPositions

### ISSUE THREAD

**Issue by S4MT3K** [Da0ne/DZMods#8]
Hey, its me again. I have a suggestion and a question. First thing is: I wrote a little code to turn on the "generator" via the modsettings.c (bool = true or false) like the other implementations. other thing is the question: Is it normal that the mapgrouppos and proto. xml is smaller than the standart one? I generated some lootpositions and have a smaller one... Im afraid that this will affect my "Normal" loot, because i changed the code. And i also added loot to types.xml that isnt in the game Normally... Thx Regards S4MT3K

EDIT: I also noticed that the loot isnt Military in theyre Areas and that you can find High Military loot in Civillian Buildings. Do you know how to fix that? Or is it just a Settings thing?

**Comment by Da0ne** [comment]
Sure i will include a bool for the generate option in the next update. And yes, if you notice the xml is smaller that probably means i did not set the scan radius high enough. TestHive.ExportProxyData( startpos radius ); Adjust that to cover the whole map.

**Comment by S4MT3K** [comment]
Didnt you mentioned in a comment that we dont fu** around with these numbers? What would be a good set to cover? I would suggest to keep the 7500 0 7500 and just increase the radius up to 8000 or, just to be safe, 10000 (better would be 9999) ?!?! What you think? Greetz S4MT3K
