### ISSUE TITLE
@vanilla++

### ISSUE THREAD

**Issue by sy8282** [Da0ne/DZMods#89]
is it just the admins that need the client sided mod or does everysingle player need to download it as well because thats going to kill it for me if thats the case

**Comment by GravityWolfNotAmused** [comment]
We are working on getting it onto the workshop right now, steam workshop uploading is something that has never really been the best. Please hold on until we are done with getting this set up.

**Comment by GravityWolfNotAmused** [comment]
But to answer your question, everyone needs the @vanilla++

**Comment by Da0ne** [comment]
Workshop will be better soon, when the "devs" update their launcher and add a proper damn server browser

**Comment by arniegames4u** [comment]
Is it not possible to launch this using -servermod?

**Comment by sy8282** [comment]
Damm that's a shame

**Comment by sy8282** [comment]
I'll have to stick with the old version

**Comment by GravityWolfNotAmused** [comment]
Client files are now on the steam workshop.
