### ISSUE TITLE
Godmode and safe zone not working 

### ISSUE THREAD

**Issue by robotstar78** [Da0ne/DZMods#9]
So, firstly, amazing mod. Well done sir! I’ve now got this (almost) working on our server. However, godmode has no effect. You can still die to everything. Falling, zombies, gunshots. And also the safe zone - when you enter it it says you’re now entering the safe zone, however god mode doesn’t do anything. Same as before where you still die to falling, zombies and gunshots, and any other damage really. Any ideas?

**Comment by robotstar78** [comment]
I’ve seen another comment about the godmode aspects, but they at least, are receiving no damage from zombies. We can’t even get that. I’m wondering if there’s a line somewhere I should be tweaking in the code?

**Comment by Da0ne** [comment]
> Im good in coding, and played a bit around with the parameters, values and other things (compared the offlineMode with this mod aswell) put the code in as what it is where you being 100% bulletproof. The result is:
> 
> YOU CAN DIE FROM LOOSING BLOOD OR/AND SHOCK!
> 
> It is the same phenomen like the airdrop flare isnt working on the Server side. (Airdrop plugin)
> 
> I Don’t know why this happens though. Ill look deeper in it next week!

At the moment there is no possible way of full god mode. Due to the fact we can not interrupt the functions that handle damage. Since they are 'hard codded' within the engine. The only option we have is the 'EEHit' function , its not the best but its all we got. For now. And for the losing blood/shock you can add a line in EEHit that will stop bleeding process upon hit same goes for shock. As for fall damage and or direct Head shot damage, we can not stop it.

**Comment by S4MT3K** [comment]
float HlthdmgDone = damageResult.GetDamage(component, "");
					float BlddmgDone  = damageResult.GetDamage(component, "Blood");
					float ShcdmgDone  = damageResult.GetDamage(component, "Shock");
					SetHealth( GetHealth("","") + HlthdmgDone );
					SetHealth( "","Blood", GetHealth("","Blood") + BlddmgDone);
					SetHealth( "","Shock", GetHealth( "","Shock") + ShcdmgDone);
				}
				
			}
			else if (AdminGmodeCheck == "true") //For admins give heal on each hit.
			{
				SetHealth( GetMaxHealth( "", "") );
				SetHealth( "","Blood", GetMaxHealth( "", "Blood" ) );
				SetHealth( "","Shock", GetMaxHealth( "","Shock") );
				GetStatStamina().Set(1000);
				GetStatEnergy().Set(1000);
				GetStatWater().Set(1000);
				GetStatStomachSolid().Set(300);		
				GetStatStomachWater().Set(300);
				GetStatStomachEnergy().Set(300);
				GetStatHeatComfort().Set(0);


Please tell me in wich Line i have to change or add something to disable the bleeding issue... Cause even when i HARDCODE it into (set health=100 or create a class from arkensors mod and copy his m-godmode state it wont work,)

**Comment by robotstar78** [comment]
Did you manage to work it out S4mtek?

**Comment by Da0ne** [comment]
> float HlthdmgDone = damageResult.GetDamage(component, "");
> float BlddmgDone = damageResult.GetDamage(component, "Blood");
> float ShcdmgDone = damageResult.GetDamage(component, "Shock");
> SetHealth( GetHealth("","") + HlthdmgDone );
> SetHealth( "","Blood", GetHealth("","Blood") + BlddmgDone);
> SetHealth( "","Shock", GetHealth( "","Shock") + ShcdmgDone);
> }
> 
> ```
> 		}
> 		else if (AdminGmodeCheck == "true") //For admins give heal on each hit.
> 		{
> 			SetHealth( GetMaxHealth( "", "") );
> 			SetHealth( "","Blood", GetMaxHealth( "", "Blood" ) );
> 			SetHealth( "","Shock", GetMaxHealth( "","Shock") );
> 			GetStatStamina().Set(1000);
> 			GetStatEnergy().Set(1000);
> 			GetStatWater().Set(1000);
> 			GetStatStomachSolid().Set(300);		
> 			GetStatStomachWater().Set(300);
> 			GetStatStomachEnergy().Set(300);
> 			GetStatHeatComfort().Set(0);
> ```
> Please tell me in wich Line i have to change or add something to disable the bleeding issue... Cause even when i HARDCODE it into (set health=100 or create a class from arkensors mod and copy his m-godmode state it wont work,)

This might sound dumb, but have you packed the PBO after making your edits?
From looking at the code, it should work.

**Comment by Da0ne** [comment]
Also you could add this line: `GetBleedingManager().RemoveSingleBleedingSource();` it will patch up the bleeding source if the player gets one every hit.

**Comment by robotstar78** [comment]
Which script are you adding these amends to? I'd like to have a look myself :)

**Comment by Da0ne** [comment]
Script: _`ModdedScripts\4_World\Entities\ManBase`_
Function:
`override void EEHitBy(TotalDamageResult damageResult, int damageType, EntityAI source, string component, string ammo, vector modelPos)`

**Comment by S4MT3K** [comment]
> 
> 
> > float HlthdmgDone = damageResult.GetDamage(component, "");
> > float BlddmgDone = damageResult.GetDamage(component, "Blood");
> > float ShcdmgDone = damageResult.GetDamage(component, "Shock");
> > SetHealth( GetHealth("","") + HlthdmgDone );
> > SetHealth( "","Blood", GetHealth("","Blood") + BlddmgDone);
> > SetHealth( "","Shock", GetHealth( "","Shock") + ShcdmgDone);
> > }
> > ```
> > 		}
> > 		else if (AdminGmodeCheck == "true") //For admins give heal on each hit.
> > 		{
> > 			SetHealth( GetMaxHealth( "", "") );
> > 			SetHealth( "","Blood", GetMaxHealth( "", "Blood" ) );
> > 			SetHealth( "","Shock", GetMaxHealth( "","Shock") );
> > 			GetStatStamina().Set(1000);
> > 			GetStatEnergy().Set(1000);
> > 			GetStatWater().Set(1000);
> > 			GetStatStomachSolid().Set(300);		
> > 			GetStatStomachWater().Set(300);
> > 			GetStatStomachEnergy().Set(300);
> > 			GetStatHeatComfort().Set(0);
> > ```
> > Please tell me in wich Line i have to change or add something to disable the bleeding issue... Cause even when i HARDCODE it into (set health=100 or create a class from arkensors mod and copy his m-godmode state it wont work,)
> 
> This might sound dumb, but have you packed the PBO after making your edits?
> From looking at the code, it should work.

Yes i Packed it. Of course :D 

> Also you could add this line: GetBleedingManager().RemoveSingleBleedingSource(); it will patch up the bleeding source if the player gets one every hit.

Adding it just direct into EEhitby? after admin gmodecheck?
