### ISSUE TITLE
Server crash with mdmp

### ISSUE THREAD

**Issue by BetterDeadThanZed** [Da0ne/DZMods#90]
I downloaded the new version via Steam workshop and set it up according to the Github instructions, except that instead of creating a new folder for my server config file, I simply used my existing server config and changed the template=

The server starts without a problem, but when a player joins, the server crashes with a mdmp file created. Here's a link to the server log: https://pastebin.com/QXJTEudM

**Comment by GravityWolfNotAmused** [comment]
> Mods: @Sullen Skies for Chernarus Plus
> Version 0.63.149525
> Fault address:  171C1A4A 00:171C1A4A Unknown module
> file:     DayZSurvival
> world:    chernarusplus
> Prev. code bytes: C4 20 5B C3 CC CC 48 89 5C 24 20 56 48 83 EC 20
> Fault code bytes: 83 79 18 00 48 8B F2 48 8B D9 75 0D 33 C0 48 8B

Looks like you should talk to Sullen Skies, my dude.

**Comment by BetterDeadThanZed** [comment]
It says that for whatever mod is at the end of the -mod= line. That's not what is causing the crash. If I put @VanillaPlusPlus, it'll say "Mods: @VanillaPlusPlus".

**Comment by sy8282** [comment]
Try using a ; instead of a ,

**Comment by BetterDeadThanZed** [comment]
> Try using a ; instead of a ,

Where?

**Comment by BetterDeadThanZed** [comment]
> Try using a ; at the end of sullen skies

Without Vanilla++ installled, the other mods run just fine without ; at the end of the -mod= parameter. Why would Vanilla++ cause the server to need a ; added to the end?

**Comment by GravityWolfNotAmused** [comment]
Crashing on launch? Also, you should change the add-on folder from @Sullen Skies for Chernarus Plus to @SullenSkiesforChernarusPlus, and change it inside of your startup command for both client and server. I think having those spaces is what's fucking it. I simply did that, and it started flawlessly.

**Comment by GravityWolfNotAmused** [comment]
I would also inform the creator of the add-on that he should update it to be that way.
