### ISSUE TITLE
Laser Zombies/ Missspelling

### ISSUE THREAD

**Issue by S4MT3K** [Da0ne/DZMods#91]
ERROR IN LINE 96-98:

The "LaserZombies" are made of the double //data.

Change in infectedHorde.c
					AIzmb.SetObjectMaterial( 0, "DZ\\data\\data\\laser.rvmat" );
					AIzmb.SetObjectMaterial( 1, "DZ\\data\\data\\laser.rvmat" );
					AIzmb.SetObjectMaterial( 2, "DZ\\data\\data\\laser.rvmat" );

To:
					AIzmb.SetObjectMaterial( 0, "DZ\\data\\laser.rvmat" );
					AIzmb.SetObjectMaterial( 1, "DZ\\data\\laser.rvmat" );
					AIzmb.SetObjectMaterial( 2, "DZ\\data\\laser.rvmat" );

Works for me. And no more Laser/Holo Zeds :D

**Comment by GravityWolfNotAmused** [comment]
If you want for us to implement a change, please push it to a forked repo and make a pull request.
