### ISSUE TITLE
god mode

### ISSUE THREAD

**Issue by kd0frg** [Da0ne/DZMods#93]
i know god mode isnt bulletproof, but id like to walk around with it for myself as an admin, i hear you cant edit the vanilla++ because its signed.. 

and the /godmode is an unrecnogized command

this is cool stuff i love it, but i wont even play on my server if i end up going pvp .. which is what every one seems to want.. i know the safe zones work so bravo! and your just awesome btw.. but what do i need to  do exactly to get the god mode to work, since im not running verify signatures anyway and im whitelisted

w/ the bleed patching? or w/ healing? would you be kind enough to give me a full step by step?

**Comment by kd0frg** [comment]
i dont want to shoot anyone and i dont want to get shot if i play lol, if i got my god mode then anyone can feel free to PVP each other for all i care on Contagion .. lol... otherwise id live in a safe zone i create :(

**Comment by Da0ne** [comment]
The god mode has nothing to do with the PBO, you can edit all the admin functionality via the mission. You have about 80% of control over the mod. The PBO only contains images and scripts to do with UI management. Currently the godmode does not work 100% but you can enable it, check AdminTool.c and do a string search for the command. Un comment and try it out. The healing command has bleeding patch added to it. /heal should stop bleeding sources. The next update will make the whole admin system way easy to work with, as I will introduce UI. 90% of the things you need to edit with the mod will be done via the admin tools. Eg making loadouts, adding admins, updating spawn points and more! Hopefully before 2019 it will be done :)

**Comment by kd0frg** [comment]
OH TY Da0ne mad respect! im very anxious for more of your work, your kinda legendary around here na mean.. we know what youve done to bohemia in the past! LOL .. im not dumb lol.. im a noob but not dumb.. TY again sorry and much appreciated

**Comment by kd0frg** [comment]
i cant get more then 1 admin to #login even if they are on my list.. only 1 can login at a time? is that normal? they are in the admins.txt?\
