### ISSUE TITLE
AdvancedLoadouts.c(83): Unknown type 'CallType'

### ISSUE THREAD

**Issue by chawdinky** [Da0ne/DZMods#95]
![b4fadb02e7d47f07661730bb919708fd](https://user-images.githubusercontent.com/14309490/49324656-dd32e600-f4f7-11e8-8979-3a4e4b4de46c.png)

Am i missing something?

**Comment by GravityWolfNotAmused** [comment]
What mods does your server have installed? Where did you get the RPC dependency? From github, or steam?

**Comment by GravityWolfNotAmused** [comment]
What's your full startup command

**Comment by chawdinky** [comment]
I may have seemed to fix that. But now im getting this. 

![49d89fb95980328c72571a352b229f3e](https://user-images.githubusercontent.com/14309490/49325161-5552d900-f503-11e8-9bc5-9550432b0c6a.png)

Also here is the startup command
`DayZServer_x64_64831.exe  -mod=@RPCFramework;@VanillaPlusPlus -insatnceid=64831 -config=vilayer_active_server_64831\64831_config.cfg -cfg=vilayer_active_server_64831\basic.cfg -profiles=vilayer_active_server_64831 -ip=162.251.61.215 -port=3002  -adminlogs -cpucount=12 -dologs -exthreads=7 -name=PRDayz -scrAllowFileWrite`

**Comment by chawdinky** [comment]
Close this, Human Error on my part with the RPC. Thanks for the help

**Comment by GravityWolfNotAmused** [comment]
NP, thanks for the issue ticket.

**Comment by Da0ne** [comment]
Vilayer...that could be the issue. Did you happen to auto install this mod via their add on manager? Or did you try it yourself?

**Comment by chawdinky** [comment]
No auto install, did it manually. There run.bat for the server is buggy. they it was deleting the last "S" of @VanillaPlusPlus it was naming it in the run command line as -mod=VanillaPlusPlu  so to fix the issue i just added another "S" and named it -mod=VanillaPlusPluss with 2 "S's" because it will delete one of them. There script is wonky right now.
