### ISSUE TITLE
#login admins .. more then one

### ISSUE THREAD

**Issue by kd0frg** [Da0ne/DZMods#97]
i cant get more then 1 admin to #login even if they are on my list.. only 1 can login at a time? is that normal? they are in the admins.txt?

**Comment by GravityWolfNotAmused** [comment]
That's a DayZ thing, this is something that is on our list things to do in the future, but for right now we are focusing on getting all UI's stable and bug free with it's respective server side code.

**Comment by GravityWolfNotAmused** [comment]
If everything goes the way that I plan, I want to add it around the same time we implement the admin ui. I thought it would be cool to have it's own usergroup manager.

**Comment by kd0frg** [comment]
oh ok sweet! thanks for quick answer!

**Comment by GravityWolfNotAmused** [comment]
Welcome! Have a good day! I am going to leave this open for others with the same question

**Comment by kd0frg** [comment]
also does /tppm work yet, im lookin at an old pastebin, i dont know if thats valid or not?

**Comment by Sniy** [comment]
I ask this on the first Release on Twitter , we will in the future a function like this : Remove Item from Crosshair ?

Thx , awesome Job People´s .

**Comment by sy8282** [comment]
Anyway to remove the parts that require the client to be modded

**Comment by GravityWolfNotAmused** [comment]
Just understand that the longer you wait the more client will be tied into everything, but the more you can configure it NOT to do, and do.
