### ISSUE TITLE
Issue upon entering server.

### ISSUE THREAD

**Issue by marenzo1** [Da0ne/DZMods#99]
Hello! Everytime I try to join server after installing the mods I get kicked due to what apears to be a modified local data file. I've tried quite a lot, togeter with a mate even. Multiple testers also got kicked. 

We get kicked due to a !workshop/dayz/xxx file that seems to be different from the FrameWork.
Does anyone know what or how? Thanks!

**Comment by chawdinky** [comment]
RPT Log? can you post your crash log? take a screenshot of your server folder with the mods and your command line. Sounds like human error.

**Comment by marenzo1** [comment]
i'm sorry for the delay.

The issue is when upon entering a server. It comes up with an error saying my files are modified of the framework. I can join a differen't server without any issues tho.

**Comment by ItsSpirit** [comment]
There's a keys folder inside of @RPCFramework copy the bikey from there and paste it into the keys folder within your DayZ root directory
